<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CancelEdit</name>
   <tag></tag>
   <elementGuidId>4e8922fa-7d3c-4bc0-9ef4-5e8a8e08c8a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[21]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Cancel&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f8a9db58-4a9d-415a-8f89-ade3b76108ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tw-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>0b4a8653-9b70-4a88-8014-48d4f0bd9085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>aed7c373-2206-4f48-a78c-54303bfd9bb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-gray-500 bg-white hover:bg-gray-100 focus:ring-4 focus:outline-none
                                focus:ring-gray-200 rounded-lg border border-gray-200 text-sm font-medium px-5
                                py-2.5 hover:text-gray-900 focus:z-10</value>
      <webElementGuid>8f033611-cb00-4214-96a3-91b6ae68bcd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Cancel
                    </value>
      <webElementGuid>ff235a2b-b46b-4124-9e36-d3ff05f0e290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;delete-642a51ca569718cbc400d7d9-modal&quot;)/div[@class=&quot;modal-dialog modal-md&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;p-6 text-center&quot;]/form[1]/button[@class=&quot;text-gray-500 bg-white hover:bg-gray-100 focus:ring-4 focus:outline-none
                                focus:ring-gray-200 rounded-lg border border-gray-200 text-sm font-medium px-5
                                py-2.5 hover:text-gray-900 focus:z-10&quot;]</value>
      <webElementGuid>0b75a84d-8085-46fb-bd26-e61de25a59a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[21]</value>
      <webElementGuid>15cd86cc-c503-4fa8-adbf-54d77fb23963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='delete-642a51ca569718cbc400d7d9-modal']/div/div/div/form/button</value>
      <webElementGuid>a543db37-bab5-4947-bcee-a9281204b57d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure you want to delete Psikolog?'])[1]/following::button[1]</value>
      <webElementGuid>e1173238-f65b-4fd7-9ddc-0a447ff3fceb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::button[1]</value>
      <webElementGuid>746e7dc2-7a19-4ff2-a08f-4af0713147df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[10]/preceding::button[1]</value>
      <webElementGuid>aebc3347-e96e-45e3-8bb1-2de947f310a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/form/button</value>
      <webElementGuid>50ad239a-e027-4ade-bff4-d83220cb2f70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
                        Cancel
                    ' or . = '
                        Cancel
                    ')]</value>
      <webElementGuid>a7593adc-cbf6-403a-82d6-8e213b07595c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
