<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_status active</name>
   <tag></tag>
   <elementGuidId>bb903595-b554-48d5-96fc-84be588ee7ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='status-1'])[11]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#add-doctor-specialty-modal > div.modal-dialog.modal-xs > div.modal-content > div.p-5 > form > div.mt-3 > div.flex.gap-5 > div.flex.items-center > #status-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#add-doctor-specialty-modal #status-1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>64eeaae7-8b97-4fb6-87a3-8a1538936522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>status-1</value>
      <webElementGuid>29277690-099b-43f1-a3b7-d6131667f59c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>ec12a076-b677-4751-9195-854e54c0ae4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>b0fddfb7-9daa-4b9f-ba76-418fa4573986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>b7b805b6-0d3b-4c26-8e0d-caf833ac0088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-4 h-4 text-blue-600 bg-gray-100 border-gray-300</value>
      <webElementGuid>f57d2bf6-c237-4eba-a323-12b32d5db053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-doctor-specialty-modal&quot;)/div[@class=&quot;modal-dialog modal-xs&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;p-5&quot;]/form[1]/div[@class=&quot;mt-3&quot;]/div[@class=&quot;flex gap-5&quot;]/div[@class=&quot;flex items-center&quot;]/input[@id=&quot;status-1&quot;]</value>
      <webElementGuid>669981bf-a570-4ed5-8a79-6f2cbe64c052</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='status-1'])[11]</value>
      <webElementGuid>e98873ff-c729-422a-8015-e04a35fa270e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='add-doctor-specialty-modal']/div/div/div[2]/form/div[4]/div/div/input</value>
      <webElementGuid>658f10b0-8c72-49fb-b7e7-17ff32a9428a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/form/div[4]/div/div/input</value>
      <webElementGuid>41759b1f-6b02-477c-83c0-6dfe8f3efca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'status-1' and @type = 'radio' and @name = 'status']</value>
      <webElementGuid>dd1a7342-6437-4c9a-8c0b-0f4a218d4d45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
