<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>edit_Applied Date</name>
   <tag></tag>
   <elementGuidId>0f00d53f-79d4-4a9e-9b89-df58ab111106</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='applied_date'])[11]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#edit-691dec44f555504d100ca893-modal > div.modal-dialog.modal-lg > div.modal-content > div.p-5 > form > div.grid.grid-cols-2.gap-4 > div:nth-of-type(2) > input[name=&quot;applied_date&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#edit-691dec44f555504d100ca893-modal > .modal-dialog > .modal-content > div:nth-child(3) > form > div > div:nth-child(2) > .form-control >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e8cd59dd-3454-47fe-8cdc-e7d9acfc374a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>df4b5183-f020-40e9-aa92-792f142e9642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>applied_date</value>
      <webElementGuid>87f8e89e-8966-48de-86da-b1f269a1a41b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>60cc3a6f-c9dc-4bd6-bd05-1c63c7afd24d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2025-12-11</value>
      <webElementGuid>09384e06-579f-4de0-9fc6-b21c0b27b9f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-691dec44f555504d100ca893-modal&quot;)/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;p-5&quot;]/form[1]/div[@class=&quot;grid grid-cols-2 gap-4&quot;]/div[2]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>ee06b6fb-fc1a-4029-b26a-b852df81756c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='applied_date'])[11]</value>
      <webElementGuid>619c3578-8bc6-42a5-852b-4bdf5e8c0878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-691dec44f555504d100ca893-modal']/div/div/div[2]/form/div/div[2]/input</value>
      <webElementGuid>b986a98d-74ce-4033-a8d9-f916bfb8cd7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/form/div/div[2]/input</value>
      <webElementGuid>4e0f7906-636b-4813-8d48-99ceecc08281</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @name = 'applied_date']</value>
      <webElementGuid>b86468b8-f458-461a-a355-553c742ed6ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
