<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>edit_version PS User App</name>
   <tag></tag>
   <elementGuidId>9a4d5f92-257e-4742-be71-d01cf081c6f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='user_ps_version'])[11]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#edit-691dec44f555504d100ca893-modal > div.modal-dialog.modal-lg > div.modal-content > div.p-5 > form > div.grid.grid-cols-2.gap-4 > div > input[name=&quot;user_ps_version&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#edit-691dec44f555504d100ca893-modal > .modal-dialog > .modal-content > div:nth-child(3) > form > div:nth-child(14) > div > .form-control >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>809b7654-bf5b-4e12-b57b-207150dbc974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9cd19467-70fc-492e-85b1-3185447bf74f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user_ps_version</value>
      <webElementGuid>40375682-fe88-481e-b6da-487aca56b754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4069ec78-cb40-41c3-a32b-fbdf88373ef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>v3.0.5</value>
      <webElementGuid>4f253b95-1baf-4ebb-888c-f7b92c19b5fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-691dec44f555504d100ca893-modal&quot;)/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;p-5&quot;]/form[1]/div[@class=&quot;grid grid-cols-2 gap-4&quot;]/div[1]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>f3598306-a523-44bd-96a5-1306e039def2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='user_ps_version'])[11]</value>
      <webElementGuid>c3e13983-0b93-4ea9-8103-b7f6ba40ac6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-691dec44f555504d100ca893-modal']/div/div/div[2]/form/div[8]/div/input</value>
      <webElementGuid>d061f340-6bb1-4624-bcf2-f2f131fa9905</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/form/div[8]/div/input</value>
      <webElementGuid>bdd90a6b-bc97-4f50-b90d-454fd9b0f67c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'user_ps_version']</value>
      <webElementGuid>89481542-013e-49b5-9dca-b76fed88aed8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
