<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>edit_Build Number PS Doctor App</name>
   <tag></tag>
   <elementGuidId>ae5a9210-0eab-40a5-8825-49ed8375162d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='doctor_ps_build_number'])[11]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#edit-691dec44f555504d100ca893-modal > div.modal-dialog.modal-lg > div.modal-content > div.p-5 > form > div.grid.grid-cols-2.gap-4 > div:nth-of-type(2) > input[name=&quot;doctor_ps_build_number&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=spinbutton >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>48338ce9-fadd-467a-8c33-06eb8686710b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>add088ed-5d64-474a-b976-ae9cbc4e5e08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>26c90293-d2e0-47e1-8913-004944a32e37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>doctor_ps_build_number</value>
      <webElementGuid>cb9a7655-68f5-4aa2-a310-545b96ed5dc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8f368cf1-7886-4578-8d8a-a5f8d9712d99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1242356346</value>
      <webElementGuid>a5edeacc-3f17-4967-8105-5a11e4ce7bff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-691dec44f555504d100ca893-modal&quot;)/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;p-5&quot;]/form[1]/div[@class=&quot;grid grid-cols-2 gap-4&quot;]/div[2]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>0a9c4ea5-a1d0-47ba-8bc4-ff5411111f44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='doctor_ps_build_number'])[11]</value>
      <webElementGuid>dfae2c13-fcc9-4d36-b5e5-ab86db4c0961</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-691dec44f555504d100ca893-modal']/div/div/div[2]/form/div[4]/div[2]/input</value>
      <webElementGuid>75ec3ead-ef30-4450-8ec2-1154692056ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/form/div[4]/div[2]/input</value>
      <webElementGuid>8f10168d-b230-4d11-bd24-ff099584470d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'doctor_ps_build_number']</value>
      <webElementGuid>01eb4de4-bbc7-4f30-9097-e4c6ac5061d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
