<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>edit_version AS User App</name>
   <tag></tag>
   <elementGuidId>1142ae68-7285-4dad-9e90-9f6f454b0f74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='user_as_version'])[11]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#edit-691dec44f555504d100ca893-modal > div.modal-dialog.modal-lg > div.modal-content > div.p-5 > form > div.grid.grid-cols-2.gap-4 > div > input[name=&quot;user_as_version&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#edit-691dec44f555504d100ca893-modal > .modal-dialog > .modal-content > div:nth-child(3) > form > div:nth-child(16) > div > .form-control >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4bf2fbcb-a538-4329-9acd-fa5bdbbee1a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c569ba9e-c500-462c-9c67-7adda3e1174f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user_as_version</value>
      <webElementGuid>6c297b2d-bf90-4f6d-889d-df8d55e2e6bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>94194831-83ea-4556-b276-bc3d9628040b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>v3.0.5</value>
      <webElementGuid>b3aa340d-a982-44c8-9cf1-14769b38c53e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-691dec44f555504d100ca893-modal&quot;)/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;p-5&quot;]/form[1]/div[@class=&quot;grid grid-cols-2 gap-4&quot;]/div[1]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>4004f824-523a-4b5d-b8bb-d7fe51dddf2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='user_as_version'])[11]</value>
      <webElementGuid>dd02dc1f-f24f-45af-b843-2f4323ef6601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-691dec44f555504d100ca893-modal']/div/div/div[2]/form/div[9]/div/input</value>
      <webElementGuid>72250a9d-b760-4817-8387-456a2bb3e976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/form/div[9]/div/input</value>
      <webElementGuid>f9d24339-9c12-4721-afed-cc7ebcac38f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'user_as_version']</value>
      <webElementGuid>8ce057e3-77c3-4b16-98b5-76a46dbab250</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
