<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Build Number user app PS</name>
   <tag></tag>
   <elementGuidId>b488039b-1b0d-4eaa-bc1e-bb0ed72fb747</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='user_ps_build_number'])[10]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#add-version-modal > div.modal-dialog.modal-lg > div.modal-content > div.p-5 > form > div.grid.grid-cols-2.gap-4 > div:nth-of-type(2) > input[name=&quot;user_ps_build_number&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#add-version-modal input[name=&quot;user_ps_build_number&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>57b97c0d-10b3-4cac-bcd7-70258ff58ae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>25ffca07-cc51-4215-9129-b9cb17ca956a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cf0c9849-6d54-477b-bf8d-f2c7c68956f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user_ps_build_number</value>
      <webElementGuid>2d39e3b0-9013-4889-8913-2340d0006fa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>dce8d6f6-640a-4660-a6bf-08e12ba1de58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-version-modal&quot;)/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;p-5&quot;]/form[1]/div[@class=&quot;grid grid-cols-2 gap-4&quot;]/div[2]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>df5d4095-bd5b-48b2-8926-e031d0b5961b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='user_ps_build_number'])[10]</value>
      <webElementGuid>103dea09-bc10-4b8c-8dcf-25d2ed13495b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='add-version-modal']/div/div/div[2]/form/div[8]/div[2]/input</value>
      <webElementGuid>df567a79-fb26-4adc-aab1-35112f6044c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/form/div[8]/div[2]/input</value>
      <webElementGuid>3dafdbc9-d86a-4464-b170-fad2b22c3d71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'user_ps_build_number']</value>
      <webElementGuid>175874bd-f77c-4069-ad94-e773ce775835</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
