<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AS version (semantic) user app</name>
   <tag></tag>
   <elementGuidId>38614caa-3167-4e74-a8b7-97fb5009ccf1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='user_as_version'])[10]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#add-version-modal > div.modal-dialog.modal-lg > div.modal-content > div.p-5 > form > div.grid.grid-cols-2.gap-4 > div > input[name=&quot;user_as_version&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#add-version-modal input[name=&quot;user_as_version&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7476c084-8b3d-4fa6-a36d-85dde6f18320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>546b33ce-2621-477b-a8b0-abb5522495bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user_as_version</value>
      <webElementGuid>00759f4c-07d1-4ef6-9daa-244b036f73e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ff8360b0-d27e-47ec-9da9-8c7992999449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-version-modal&quot;)/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;p-5&quot;]/form[1]/div[@class=&quot;grid grid-cols-2 gap-4&quot;]/div[1]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>4f144d9f-a03c-4d56-8f1f-400dd84243a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='user_as_version'])[10]</value>
      <webElementGuid>b3967265-1a00-4383-b3d5-af26e4da392b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='add-version-modal']/div/div/div[2]/form/div[9]/div/input</value>
      <webElementGuid>139af3ef-433a-4ace-8726-962d77698894</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/form/div[9]/div/input</value>
      <webElementGuid>05c8703b-a897-49fc-9290-5ae1aec8de77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'user_as_version']</value>
      <webElementGuid>9685f074-eddd-4679-8740-f04dffa63ebb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
