<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Backend Version</name>
   <tag></tag>
   <elementGuidId>e2904cb9-e899-422a-a16c-318cc3dc7877</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='backend_version'])[10]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#add-version-modal > div.modal-dialog.modal-lg > div.modal-content > div.p-5 > form > div.grid.grid-cols-2.gap-4 > div > input[name=&quot;backend_version&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#add-version-modal input[name=&quot;backend_version&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e7b5a2d4-f786-4d1d-8223-e0b14dd7cb05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>637fc83c-648a-48bc-a08f-da3b20837a48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>backend_version</value>
      <webElementGuid>fd29e568-c054-47b2-a1c5-fbe06756132d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1abf8d3d-c574-4b2f-960b-d26ac6c5be57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-version-modal&quot;)/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;p-5&quot;]/form[1]/div[@class=&quot;grid grid-cols-2 gap-4&quot;]/div[1]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>66b4f071-e427-4591-ae32-24063ac9a1ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='backend_version'])[10]</value>
      <webElementGuid>d6001bdb-a8bb-4b76-9e25-b2df8f76f1e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='add-version-modal']/div/div/div[2]/form/div/div/input</value>
      <webElementGuid>c3f9232d-3da6-46c6-8617-f8acbdec5d2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/form/div/div/input</value>
      <webElementGuid>c0d8e4d0-18ac-4204-ad70-a7578dfbae2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'backend_version']</value>
      <webElementGuid>0fd6e296-cc44-42da-b4d9-672997f8e5a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
