<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View ke history</name>
   <tag></tag>
   <elementGuidId>541c3e80-6a98-4488-88d8-91ba2b4ee4ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.flex.items-center.text-primary.mr-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[2]/following::a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;View&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>72d93624-cb45-43e2-8a7b-a745ff17d8de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center text-primary mr-5</value>
      <webElementGuid>ef797830-8325-4404-af05-75ee3fb04302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://backoffice-stg.digitalsekuriti.id/user-aicare/68ff23dbd0a2d83b137795c9/profile</value>
      <webElementGuid>935571ab-df7b-4387-8304-0edfc959d27c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    View
                                </value>
      <webElementGuid>127b4b9f-124a-480d-93c2-dd23ac156b1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;light&quot;]/body[@class=&quot;py-5 md:py-0&quot;]/div[@class=&quot;flex overflow-hidden&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;intro-y box p-5 mt-5&quot;]/div[@class=&quot;overflow-x-auto scrollbar-hidden&quot;]/table[@class=&quot;table my-5 sortable&quot;]/tbody[1]/tr[1]/td[@class=&quot;whitespace-nowrap&quot;]/div[@class=&quot;flex justify-center&quot;]/a[@class=&quot;flex items-center text-primary mr-5&quot;]</value>
      <webElementGuid>aa4c4322-f8c9-475f-8af7-047bcbd1ad88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[2]/following::a[1]</value>
      <webElementGuid>5a37ae73-c655-44da-bc72-4bfbb3708baa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[2]/following::a[1]</value>
      <webElementGuid>ab7a307d-e456-4042-9a76-fe434a147c1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deactivate User?'])[1]/preceding::a[2]</value>
      <webElementGuid>450f1cad-d073-48de-b4aa-4f04aee90f35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View']/parent::*</value>
      <webElementGuid>69dc8f7f-dd7f-46b8-8705-9f0e45c11b7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://backoffice-stg.digitalsekuriti.id/user-aicare/68ff23dbd0a2d83b137795c9/profile')]</value>
      <webElementGuid>b844d3ae-100c-4c41-a40d-b6856d8ca76b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/div/a</value>
      <webElementGuid>87ef0d70-74b2-4405-82e3-c7292fd2bc7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://backoffice-stg.digitalsekuriti.id/user-aicare/68ff23dbd0a2d83b137795c9/profile' and (text() = '
                                    View
                                ' or . = '
                                    View
                                ')]</value>
      <webElementGuid>85fcb6c5-2b74-4ed7-abd6-bc29c36e0bc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
