<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Inactive</name>
   <tag></tag>
   <elementGuidId>15eaba44-796d-4359-97b1-8e15cb13f1d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#status-opt-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='status-opt-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#status-opt-2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c623ab45-8a6f-46cd-9a1f-f58ec3832860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>inactive</value>
      <webElementGuid>6972aa88-9da9-44e9-a021-e17348c74a11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option active</value>
      <webElementGuid>33e16d38-a2f8-4f97-8be9-9ee3dcfd6687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>3b1e21cd-bdd3-43a6-a774-60666ffdb403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>status-opt-2</value>
      <webElementGuid>8ee93aa9-2e02-4b3f-afcc-cd02bd9c200a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>987c8fae-def5-490d-8ba7-4f47e24622db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Inactive</value>
      <webElementGuid>b65fd2a1-882a-491a-a4a3-585883d59f86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;status-opt-2&quot;)</value>
      <webElementGuid>7b7b1612-00a2-4aaa-bb3d-3dd08725fc0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='status-opt-2']</value>
      <webElementGuid>b74d5834-14bb-4c3f-9e41-15b41a62f790</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='status-ts-dropdown']/div[2]</value>
      <webElementGuid>ce8287e7-e9b4-448f-b4e4-65a035a6f32c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[2]/following::div[1]</value>
      <webElementGuid>8dd6cdcc-4625-4f74-81f1-ba8ed695f379</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inactive Date'])[1]/following::div[7]</value>
      <webElementGuid>2db1b374-badb-47ba-a5fa-e1eea56e338f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]</value>
      <webElementGuid>e690bce3-8c4a-44a0-8b1c-439267d38e36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'status-opt-2' and (text() = 'Inactive' or . = 'Inactive')]</value>
      <webElementGuid>dd4a1725-ae30-4ce9-b674-87ab6d2ec0b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
