<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Teleconsultation</name>
   <tag></tag>
   <elementGuidId>3fa3be8f-5816-48b0-a8c4-1a44f064eb0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tomselect-1-opt-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tomselect-1-opt-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#tomselect-1-opt-1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1fac3bbf-e436-4d40-aabe-46590debce61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>teleconsultation</value>
      <webElementGuid>a5cd8784-d57d-4c17-9ebe-8b17bc8dd70b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option selected active</value>
      <webElementGuid>7154f6cc-73bc-4802-bf84-0d36ccc39dca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>4d646886-f595-429a-a504-e667421880c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tomselect-1-opt-1</value>
      <webElementGuid>555eb5ec-086c-452f-b0b7-751185db8485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bdada926-b494-4ccc-8a54-80ff7f14cf2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Teleconsultation
                        </value>
      <webElementGuid>dbcce1ba-f553-4eb1-8554-261f2318c948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tomselect-1-opt-1&quot;)</value>
      <webElementGuid>87f12565-ccce-4272-b37a-fb37aaae36a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='tomselect-1-opt-1']</value>
      <webElementGuid>f56c41c5-c15e-4c99-a721-52bb2bf6f3b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tomselect-1-ts-dropdown']/div</value>
      <webElementGuid>daa94894-2a4c-43c2-b7af-a222ad2d35ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Teleconsultation'])[4]/following::div[4]</value>
      <webElementGuid>c200e8cd-f278-463b-9d56-4cb178f53204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter By'])[1]/following::div[7]</value>
      <webElementGuid>14141d2b-bdce-469d-b1c4-a48aea676319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Symptom Checker'])[2]/preceding::div[1]</value>
      <webElementGuid>a71d2a80-2b74-44fa-9069-c4ba7d852e25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lab Interpretation'])[2]/preceding::div[2]</value>
      <webElementGuid>130b994a-042e-4bd7-a42d-c44e8ca17f9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div[2]/div[2]/div</value>
      <webElementGuid>b828064d-9c34-4385-bd45-01dd892dbbfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'tomselect-1-opt-1' and (text() = '
                            Teleconsultation
                        ' or . = '
                            Teleconsultation
                        ')]</value>
      <webElementGuid>aed4c1ce-402f-4095-ae71-72bba5685ee5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
