<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>filter_account status</name>
   <tag></tag>
   <elementGuidId>6f88827a-de96-4660-a926-5c2827bcf75f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.items-placeholder</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='status-ts-control']/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Account Status&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8d3d0b4c-3942-49b8-adaa-708303493049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>items-placeholder</value>
      <webElementGuid>171684d3-1823-48e3-904d-11670c08da7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>86b44cf5-1e7b-4a0b-81ee-67d8850ae091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Account Status</value>
      <webElementGuid>969d2b13-72b8-4a2b-8385-d5d5dd3d1782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;status-ts-control&quot;)/input[@class=&quot;items-placeholder&quot;]</value>
      <webElementGuid>6daf45b5-559a-487e-9aae-8c8204db1724</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='status-ts-control']/input</value>
      <webElementGuid>fb827712-4646-4268-910d-3b41f1008155</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>4cb6d1f9-6c1a-44da-b55d-d8e6b265c0e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Account Status']</value>
      <webElementGuid>5ddac78c-89b3-42b6-b35a-d518e2ca783c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
