<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Show</name>
   <tag></tag>
   <elementGuidId>3eaebc79-8a9d-4c1c-8aab-ae66a920deb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.flex.items-center.text-primary.mr-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='V1.0.0'])[5]/following::button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Show&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ff49618c-3e52-470e-809f-d232aa1cfc2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center text-primary mr-3</value>
      <webElementGuid>d620f651-cdf5-4f93-87ba-30cd55e8db13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tw-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>eca0fdee-f97d-4011-9cc2-ba0382f6972f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tw-target</name>
      <type>Main</type>
      <value>#show-68de3c16616609c00f068bc8-modal</value>
      <webElementGuid>a6f30409-eb8b-4cb7-b363-3a5f8b9d3cc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                            Show
                                    </value>
      <webElementGuid>75ef7e58-de0b-4e10-b432-844d159d10dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;light&quot;]/body[@class=&quot;py-5 md:py-0&quot;]/div[@class=&quot;flex overflow-hidden&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;mt-5&quot;]/div[@class=&quot;intro-y box p-5 mt-5&quot;]/div[@class=&quot;overflow-x-auto scrollbar-hidden mt-5&quot;]/table[@class=&quot;table sortable&quot;]/tbody[1]/tr[1]/td[8]/div[@class=&quot;flex justify-center&quot;]/button[@class=&quot;flex items-center text-primary mr-3&quot;]</value>
      <webElementGuid>43e96726-d586-45b9-9648-3a52c42991ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='V1.0.0'])[5]/following::button[1]</value>
      <webElementGuid>ac9c7639-5328-4085-a234-ff5bed73e955</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='V1.0.0'])[4]/following::button[1]</value>
      <webElementGuid>1e9ced23-5b05-4287-b094-ddc85be3176a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Doctor App'])[2]/preceding::button[1]</value>
      <webElementGuid>809b648e-2113-4263-b886-83023b658d75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date'])[2]/preceding::button[1]</value>
      <webElementGuid>587e793f-1404-4978-b93e-bb538653198a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Show']/parent::*</value>
      <webElementGuid>e1e95fab-fea0-4c7f-aa10-4279b114ff67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/div/button</value>
      <webElementGuid>2565ea27-d7fd-40cb-abff-941a5c091e69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '
                                            Show
                                    ' or . = '
                                            Show
                                    ')]</value>
      <webElementGuid>8ca26430-b6e0-44f0-a3a1-e08a9e718e44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
