<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_iOS</name>
   <tag></tag>
   <elementGuidId>95c863ae-22ed-47d4-be04-e902f4122ae3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#platform-opt-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='platform-opt-3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#platform-opt-3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>eb9045ea-9fd4-416f-8073-a01681800107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>ios</value>
      <webElementGuid>b680c280-3a45-4899-a59e-70175215de16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option active</value>
      <webElementGuid>89839088-8e42-412f-adbf-f176bf9643df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>ae0787f8-6a98-4fec-829a-2822a6473753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>platform-opt-3</value>
      <webElementGuid>598a1590-5a08-4644-b05f-847c31e07032</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fcdba758-b83c-48df-8f0d-981545daf079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>iOS</value>
      <webElementGuid>604aa5b9-cf3e-4b70-8102-e284d36bd1d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;platform-opt-3&quot;)</value>
      <webElementGuid>120feb8f-c04d-4850-b067-011445a3808c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='platform-opt-3']</value>
      <webElementGuid>c0f46749-7232-427a-a0e2-686e43ccf20b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='platform-ts-dropdown']/div[3]</value>
      <webElementGuid>d494a4b3-e65e-4eed-906c-bbf92389ea1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Android'])[2]/following::div[1]</value>
      <webElementGuid>7e052d97-3a77-4c16-b71f-430b532b107c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Platform'])[3]/following::div[2]</value>
      <webElementGuid>7997e756-efa3-464e-b321-951c70ce3427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add New Version'])[1]/preceding::div[1]</value>
      <webElementGuid>fa6323e4-1031-4678-8c1f-15904201ff77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div[3]</value>
      <webElementGuid>6d3def74-f569-431f-bcc7-ae6071c4b4b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'platform-opt-3' and (text() = 'iOS' or . = 'iOS')]</value>
      <webElementGuid>ae533bba-a9f3-4cd1-a126-b582fd775bbb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
