<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Android</name>
   <tag></tag>
   <elementGuidId>18f08d94-f77f-4026-8baf-46e7e9167434</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#platform-opt-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='platform-opt-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=listbox >> internal:role=option[name=&quot;Android&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>486b131a-72c1-496b-aa0b-3e5ee4c761c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>android</value>
      <webElementGuid>2d5778cf-1bf6-4035-95fe-fa1d5ab3eb0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option active</value>
      <webElementGuid>b6d9fe93-3025-4c3e-9b89-5828354929a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>c7f20e69-a43a-4cb6-8392-1c46c529ace6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>platform-opt-2</value>
      <webElementGuid>93ab667d-51e5-41b4-9f89-f65aa18c3c28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bfca01ff-568b-4143-9dee-66c2d8105a05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Android</value>
      <webElementGuid>dc9a2f38-f70b-4bb0-941b-1696a801c40d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filter&quot;)/div[@class=&quot;ts-wrapper cs-select w-32 text-primary single focus input-active dropdown-active&quot;]/div[@class=&quot;ts-dropdown single&quot;]/div[@id=&quot;platform-ts-dropdown&quot;]/div[@id=&quot;platform-opt-2&quot;]</value>
      <webElementGuid>e7ae42ea-1f7f-4ef2-a3b0-a39da0de52e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='platform-opt-2']</value>
      <webElementGuid>4356711a-e8b3-44f9-aca4-98ecd8fbd354</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='platform-ts-dropdown']/div[2]</value>
      <webElementGuid>8966e96e-4168-4e31-b760-8de2f9cb470c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Platform'])[3]/following::div[1]</value>
      <webElementGuid>8787f84a-a8d7-4e1c-afee-ef38e006be07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='October 21, 2025 - December 20, 2025'])[1]/following::div[10]</value>
      <webElementGuid>0963a213-fce7-4ce7-9af5-1ce695aa44b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='iOS'])[2]/preceding::div[1]</value>
      <webElementGuid>d69d74e2-d01f-406e-a0e9-626fc15d5be7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div[2]</value>
      <webElementGuid>b374fd3c-3d88-46e2-a19b-e2094e6dabbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'platform-opt-2' and (text() = 'Android' or . = 'Android')]</value>
      <webElementGuid>d6b3c457-93fb-4a5a-996b-b8d4e6ad3057</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
