<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__version</name>
   <tag></tag>
   <elementGuidId>4271c471-8202-4232-b08a-9c74d174c8e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#version</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='version']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Type Version&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>13e501c1-ffc9-42ef-b1fe-73fa3f038a8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3e205baf-9a9b-46fa-bd77-d0fc18e4c43f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>version</value>
      <webElementGuid>ef04ff6e-3043-4c00-96d6-87fa8c3da03d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>version</value>
      <webElementGuid>a2a3af7c-a8b3-4bac-bc04-c019dc43fdd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a67c386f-8c7a-46b0-9bed-29c55bde29d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type Version</value>
      <webElementGuid>a30f5571-06e8-4b88-b748-12d7fa77725c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Semantic version (SemVer): 1.2.3, 1.2.3-beta.1, 1.2.3+build.5</value>
      <webElementGuid>b4378dd2-846a-4904-98a5-6de5f262b531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;version&quot;)</value>
      <webElementGuid>3d23ed89-97f1-4f81-aad0-311f30e69d85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='version']</value>
      <webElementGuid>306d22c4-2a8b-488d-be80-f6f52a39df2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='add-version-modal']/div/div/div[2]/form/div[4]/div/input</value>
      <webElementGuid>a3b2dea2-aaaf-4a1a-bbaf-428efa366d93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>10aa148c-a2cd-426f-8b22-6cf2eebdd11a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'version' and @id = 'version' and @placeholder = 'Type Version' and @title = 'Semantic version (SemVer): 1.2.3, 1.2.3-beta.1, 1.2.3+build.5']</value>
      <webElementGuid>a61bed12-1b99-48ab-af42-73c9049a5730</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
