<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Body Measurement</name>
   <tag></tag>
   <elementGuidId>e67b6194-5713-458b-a589-bb0da1de934b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tomselect-2-opt-2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tomselect-2-opt-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#tomselect-2-opt-2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e742d2aa-5f28-46fb-9fa6-44296b3b8b9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>body_measurement</value>
      <webElementGuid>de13f430-0a3a-46ae-8a17-55c7c0ad3af5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option selected active</value>
      <webElementGuid>d8d68ab0-0a66-4056-84d4-b43ab0b7268f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>00f04dd2-0c3e-4824-b18f-a387e0ea3fee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tomselect-2-opt-2</value>
      <webElementGuid>e73bfd8c-fbd4-4c3b-b1e6-dc553a8036e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d84ca987-7165-43fc-b6c2-39f941c12766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Body Measurement
                            </value>
      <webElementGuid>aa602cd4-72c1-4647-ba7c-4389be09c409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tomselect-2-opt-2&quot;)</value>
      <webElementGuid>020f3936-3104-4b87-803f-dd2020d211a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='tomselect-2-opt-2']</value>
      <webElementGuid>2fe269f9-1fa6-49dd-8970-dcdf8142a60d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tomselect-2-ts-dropdown']/div[2]</value>
      <webElementGuid>9fd094f1-72ea-4082-a4d5-754ec78b9985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lab Interpretation'])[2]/following::div[1]</value>
      <webElementGuid>90373eb8-6c54-4709-9714-4fdb0cb9417a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Body Measurement'])[2]/following::div[5]</value>
      <webElementGuid>9b225e4c-1707-48fc-a059-ee377746e3b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Breathing Interpretation'])[2]/preceding::div[1]</value>
      <webElementGuid>fa3c20f8-cccd-4faf-aa0d-c43eb061860b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pulse Interpretation'])[2]/preceding::div[2]</value>
      <webElementGuid>7ea5b195-2f62-4e27-ac0e-d379be62480e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]</value>
      <webElementGuid>1e68273b-c53f-4469-a08f-5bb9e28bd19b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'tomselect-2-opt-2' and (text() = '
                                Body Measurement
                            ' or . = '
                                Body Measurement
                            ')]</value>
      <webElementGuid>03a5b572-e186-4160-98bd-974e165edcc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
