<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Users Name</name>
   <tag></tag>
   <elementGuidId>2341ce00-2d74-4201-b300-1421e3743e1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tomselect-1-opt-3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tomselect-1-opt-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#tomselect-1-opt-3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f0702845-4935-4c4f-97c8-f560686d6fdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>user_name</value>
      <webElementGuid>4a1cb0df-8482-467a-8055-663931b7b2bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option active</value>
      <webElementGuid>6e1ca8a4-f485-4d72-a3b5-fdc19a821b17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>259160d2-c7db-4218-a4a6-bec9cb4386a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tomselect-1-opt-3</value>
      <webElementGuid>320bc3ac-e10c-4445-b821-8d324a99d662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>74f0a5e4-57eb-467c-8b5c-f2d917c4d73f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                User's Name
                            </value>
      <webElementGuid>2c1d51d7-98c7-4290-b215-f6ff62795faa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tomselect-1-opt-3&quot;)</value>
      <webElementGuid>b6e4fe68-cc1e-47fa-b286-74cff96e5837</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='tomselect-1-opt-3']</value>
      <webElementGuid>9a56e108-eba5-4593-b153-ac70f7e49060</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tomselect-1-ts-dropdown']/div[3]</value>
      <webElementGuid>12bae9fa-971d-40f2-8de1-eea63559a026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User ID'])[2]/following::div[1]</value>
      <webElementGuid>f740f63d-993f-429f-8c6a-a6ce1e742a96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gimmick ID'])[3]/following::div[2]</value>
      <webElementGuid>91f2da2e-4dbf-46d6-aaad-44121a318950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date'])[2]/preceding::div[1]</value>
      <webElementGuid>e6c21e82-96ba-4b4a-8d49-3e99b40f2b00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Value'])[1]/preceding::div[2]</value>
      <webElementGuid>dd3ec8b4-61d2-426d-ba65-fcd995fa9997</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[3]</value>
      <webElementGuid>00c94806-318e-40c7-959d-5a3d745f1bdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'tomselect-1-opt-3' and (text() = concat(&quot;
                                User&quot; , &quot;'&quot; , &quot;s Name
                            &quot;) or . = concat(&quot;
                                User&quot; , &quot;'&quot; , &quot;s Name
                            &quot;))]</value>
      <webElementGuid>043b2a33-5c97-4138-a628-6b07a40fa992</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
