<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ValueDateFrom</name>
   <tag></tag>
   <elementGuidId>ad19cd05-a667-4bb5-bdc6-9367c81b6e65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='value']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;value&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>12a8ad5a-b3a4-458c-a529-34da3071ebb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>113879af-0764-494e-a4a8-06c05b9c5449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>value</value>
      <webElementGuid>1ff5102a-679e-48ca-8617-7c4257252fb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gimmick_filter_value form-control w-40</value>
      <webElementGuid>31bcaa82-943f-461c-8ead-333fe90dea98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search...</value>
      <webElementGuid>84ffc744-2543-48b5-9e8c-6dac5a57b785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;light&quot;]/body[@class=&quot;py-5 md:py-0&quot;]/div[@class=&quot;flex overflow-hidden&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;mt-5&quot;]/div[@class=&quot;intro-y col-span-12 items-center mt-2&quot;]/form[1]/div[@class=&quot;grid grid-cols-12 gap-4 mt-5&quot;]/div[@class=&quot;col-span-12 sm:col-span-6 xl:col-span-3 items-center filter_value&quot;]/input[@class=&quot;gimmick_filter_value form-control w-40&quot;]</value>
      <webElementGuid>14c29acd-ae2a-450a-81b8-e999573014ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='value']</value>
      <webElementGuid>ad7c7a49-ff5c-41b0-8bd5-73caecd0246c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>3c198616-bcc7-4e47-9de6-d2f89ad81f45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @name = 'value' and @placeholder = 'Search...']</value>
      <webElementGuid>725ec59d-8058-4f33-81a0-37a295cd424d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
