<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cancel ubah status</name>
   <tag></tag>
   <elementGuidId>90ddc288-b85c-4e0f-b738-9c482e44def0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[31]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Cancel&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6f02dcc6-533f-40d2-a98a-7a1dff7997db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tw-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>dee91d7e-f812-4875-aee1-10a17e2e3ffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0b9b2c34-830f-4f98-a7b9-a5cfada1dffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-gray-500 bg-white hover:bg-gray-100 focus:ring-4
                                    focus:outline-none focus:ring-gray-200 rounded-lg border
                                    border-gray-200 text-sm font-medium px-5 py-2.5 hover:text-gray-900 focus:z-10 </value>
      <webElementGuid>d87a09e9-3052-4bd9-9cad-ee39b7cf82ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Cancel
                    </value>
      <webElementGuid>f3a24410-d634-4f86-a12c-fe82ac3a63c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;activate-691d779ccadf232d030c7f92-modal&quot;)/div[@class=&quot;modal-dialog modal-md&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;p-6 text-center&quot;]/form[1]/button[@class=&quot;text-gray-500 bg-white hover:bg-gray-100 focus:ring-4
                                    focus:outline-none focus:ring-gray-200 rounded-lg border
                                    border-gray-200 text-sm font-medium px-5 py-2.5 hover:text-gray-900 focus:z-10&quot;]</value>
      <webElementGuid>ac9d5cf0-dca3-40a9-a09b-cbc3fad8f1e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[31]</value>
      <webElementGuid>8f2c83dc-5a58-4571-9a95-9814615f9d0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='activate-691d779ccadf232d030c7f92-modal']/div/div/div/form/button</value>
      <webElementGuid>4e87e729-e1fa-48fb-a6ec-dc3255876236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure you want to activate Banner test 123?'])[1]/following::button[1]</value>
      <webElementGuid>80aa786f-9292-4580-b855-1cfef514af9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::button[1]</value>
      <webElementGuid>6f34664e-035d-4c91-8dc9-6d48ea95081e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activate'])[1]/preceding::button[1]</value>
      <webElementGuid>730696a0-b17e-4a63-b6df-e773309b6eec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/form/button</value>
      <webElementGuid>cbdbad7b-5f68-4e82-bb29-24f68751cf07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
                        Cancel
                    ' or . = '
                        Cancel
                    ')]</value>
      <webElementGuid>7807ee74-64d4-4435-9125-2ac261808dbe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
