<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_konfirmDelete</name>
   <tag></tag>
   <elementGuidId>8f7d6eac-3565-490b-8ab2-e4c4994747c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[32]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#delete-691d779ccadf232d030c7f92-modal > .modal-dialog > .modal-content > .p-6 > form > .text-white</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>70bb5605-9692-460c-8670-e7b256d64100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ccdc5952-1804-411a-aa93-7417296906e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-white bg-red-600 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300
                            font-medium rounded-lg text-sm inline-flex items-center px-5 py-2.5 text-center mr-2</value>
      <webElementGuid>f4c5b449-3e28-4bcd-945e-6a5d57b0eacc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Delete
                    </value>
      <webElementGuid>c400f201-753d-4779-8094-c96534f828e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;delete-691d779ccadf232d030c7f92-modal&quot;)/div[@class=&quot;modal-dialog modal-md&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;p-6 text-center&quot;]/form[1]/button[@class=&quot;text-white bg-red-600 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300
                            font-medium rounded-lg text-sm inline-flex items-center px-5 py-2.5 text-center mr-2&quot;]</value>
      <webElementGuid>8bc885a3-5901-429f-a33f-9508b36f9668</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[32]</value>
      <webElementGuid>0086e3bb-e5f0-4332-a901-5702fa60176f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='delete-691d779ccadf232d030c7f92-modal']/div/div/div/form/button[2]</value>
      <webElementGuid>e71b89c8-cf60-498d-833d-3d8abea0f407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[31]/following::button[1]</value>
      <webElementGuid>82c4c3d5-2440-4d75-a2b3-300806601f2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure you want to delete Banner test 123?'])[2]/following::button[2]</value>
      <webElementGuid>d80f31ae-01f9-4873-b758-56cacadd9bca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/form/button[2]</value>
      <webElementGuid>4f22853a-1cca-4e7c-b6c7-c8a0bccbb74b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = '
                        Delete
                    ' or . = '
                        Delete
                    ')]</value>
      <webElementGuid>44c5c45b-d34e-4c54-8f1d-481b547d176a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
