<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Natrium</name>
   <tag></tag>
   <elementGuidId>a1356506-47ca-46a2-bb38-ae8a0b684864</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#add-attribute-opt-32</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='add-attribute-opt-32']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#add-attribute-opt-32</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3af8bbb7-7c70-4f63-813b-4a3e884c7c61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>natrium</value>
      <webElementGuid>93a75e6f-1f1c-4d7a-b8d4-cdd7ff60e18e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option active</value>
      <webElementGuid>946589f9-63f8-4ae0-82ae-4937888368cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>28743d99-0b9d-45e6-a95d-6b6b5bf7947a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add-attribute-opt-32</value>
      <webElementGuid>9f1b85c6-b9d5-4de0-a527-09f8a323f8f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>62954ba3-b7c6-47b3-a1eb-9dcec3c22513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                            Natrium
                                        </value>
      <webElementGuid>d6b944be-a1d7-4704-9b19-345a3946cc8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-attribute-opt-32&quot;)</value>
      <webElementGuid>ef64c6cb-1ebd-4e29-b485-66c6347c22aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='add-attribute-opt-32']</value>
      <webElementGuid>51d45435-1a5f-404d-8cc7-edc304e5f044</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='add-attribute-ts-dropdown']/div[5]/div[3]</value>
      <webElementGuid>955674e9-76a2-4d7f-bcdd-6d55c0c780c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Klorida'])[12]/following::div[1]</value>
      <webElementGuid>73c8b4ad-a5c0-4d55-bc57-e468e8f7c1fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Electrolyte'])[1]/following::div[2]</value>
      <webElementGuid>f11f8126-ca7e-4fe7-8437-e7345e67b117</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kalium'])[12]/preceding::div[1]</value>
      <webElementGuid>ad42b00e-ffb7-41cb-86fb-9fd3176049a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Liver Function'])[1]/preceding::div[2]</value>
      <webElementGuid>08b82319-a9fc-4bf2-a80d-fdd490e0747d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[3]</value>
      <webElementGuid>2474626a-eedb-40bc-b2b7-e20437b88e56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'add-attribute-opt-32' and (text() = '
                                            Natrium
                                        ' or . = '
                                            Natrium
                                        ')]</value>
      <webElementGuid>b114f16a-fe4a-409a-82ef-f9d9e075fabb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
