<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Asam Urat</name>
   <tag></tag>
   <elementGuidId>b36270e9-4c5b-4cf7-96ed-df739f8b96b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#add-attribute-opt-27</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='add-attribute-opt-27']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#add-attribute-opt-27</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>44cd6938-bea2-42cd-8d5a-0e9398dd5f31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>asam_urat</value>
      <webElementGuid>8bf091d8-2565-4988-95cf-646815e87cab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option active</value>
      <webElementGuid>4f6e0a13-0dfc-4f9d-83d5-bd798b06b3a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>3a24c1f6-aaf5-4f8c-b6da-b28f762be5fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add-attribute-opt-27</value>
      <webElementGuid>f23183eb-e2cc-4fe3-bae9-b4f9d9c2ce87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e0ddbc66-3f9c-4762-a47e-a0e7be261f39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                            Asam Urat
                                        </value>
      <webElementGuid>41236274-791a-4594-8813-e3c782ace9a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-attribute-opt-27&quot;)</value>
      <webElementGuid>946c7ac1-38de-45f8-9aab-0d44b3d8b99e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='add-attribute-opt-27']</value>
      <webElementGuid>18d347e0-8a0a-4ea4-a869-8f69d0da6703</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='add-attribute-ts-dropdown']/div[4]/div[2]</value>
      <webElementGuid>b5c895b4-fccd-4ca1-81f4-dc5c4074986f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kidney Function'])[1]/following::div[1]</value>
      <webElementGuid>b43b2dfe-ad76-4f6e-adb7-c39fa4c7d34a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trigliserida'])[12]/following::div[3]</value>
      <webElementGuid>1c7f8396-a6aa-4956-9775-a4d3d7de7c5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ureum'])[12]/preceding::div[1]</value>
      <webElementGuid>e66f49ab-3e1c-45e9-89f3-703afcaeb19f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Creatinine'])[12]/preceding::div[2]</value>
      <webElementGuid>5329de9f-f0f2-49e9-a064-492f89e46a00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]</value>
      <webElementGuid>5fd1e5d4-15cc-403e-b452-602b5ed3be4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'add-attribute-opt-27' and (text() = '
                                            Asam Urat
                                        ' or . = '
                                            Asam Urat
                                        ')]</value>
      <webElementGuid>a10481e3-8d42-4fdc-aab7-bccea920a529</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
