<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>edit_status inactive</name>
   <tag></tag>
   <elementGuidId>3034b154-4cd5-4f1d-b7f5-58df2f0235a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#status-691d779ccadf232d030c7f92-inactive</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='status-691d779ccadf232d030c7f92-inactive']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=radio[name=&quot;Inactive&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>daff7af2-2f2b-41ce-92dc-f5d46901ccb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>status-691d779ccadf232d030c7f92-inactive</value>
      <webElementGuid>165b2b20-fa26-485b-96b2-d43dcda2cafc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>6b8fc482-1221-4db2-9fa4-de4dfc4f26f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>inactive</value>
      <webElementGuid>69d93ef8-d726-4c3c-911e-1764c3ed0256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>8f3930a0-b29e-4c12-9f7e-0f6604e1e47a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-4 h-4 text-blue-600 bg-gray-100 border-gray-300</value>
      <webElementGuid>4ed6c92f-be94-4584-ac62-4d0f440241b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;status-691d779ccadf232d030c7f92-inactive&quot;)</value>
      <webElementGuid>4510d8b6-3888-4e9e-bf26-f22d056129d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='status-691d779ccadf232d030c7f92-inactive']</value>
      <webElementGuid>6ebfb87a-5d7b-4e3f-957e-5ae0ec6c0a1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-691d779ccadf232d030c7f92-modal']/div/div/div[2]/form/div[9]/div/div[2]/input</value>
      <webElementGuid>f5034d45-495f-41ed-b05e-8ba1b7750dd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/form/div[9]/div/div[2]/input</value>
      <webElementGuid>e8d4a193-4880-473b-bd95-8b908405acab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'status-691d779ccadf232d030c7f92-inactive' and @type = 'radio' and @name = 'status']</value>
      <webElementGuid>910ff492-7d6a-46fc-9866-9e2bf4d0700c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
