<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>edit_content</name>
   <tag></tag>
   <elementGuidId>376ab002-3580-41ff-8454-a2ce87eee9a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-691d779ccadf232d030c7f92-modal > div.modal-dialog.modal-lg > div.modal-content > div.p-5.edit-banner > form > div.mt-3 > div.dynamicType > div.gap-5 > div.flex.items-center > #content-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='content-5'])[9]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>form >> internal:has-text=&quot;Name Image Choose File img_691d779bc1a0b.png Location * Gimmick CoreCore Type Sl&quot;i >> #content-5</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0eb0a8e7-020d-440b-a4c2-072e087f54ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>content-5</value>
      <webElementGuid>17405ed3-da2e-4aed-8337-274fa3cbe408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>9bf4c817-ae49-4e1e-a537-8de578780859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>interpretation</value>
      <webElementGuid>558551e9-da13-4166-8cd4-4607e3cac5da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>content</value>
      <webElementGuid>ac772f7a-2478-44bd-a746-57df1786f208</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-4 h-4 text-blue-600 bg-gray-100 border-gray-300</value>
      <webElementGuid>7f2971fa-7393-4b00-8d2a-19ad198273a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-691d779ccadf232d030c7f92-modal&quot;)/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;p-5 edit-banner&quot;]/form[1]/div[@class=&quot;mt-3&quot;]/div[@class=&quot;dynamicType&quot;]/div[@class=&quot;gap-5&quot;]/div[@class=&quot;flex items-center&quot;]/input[@id=&quot;content-5&quot;]</value>
      <webElementGuid>abf622ce-7e29-4880-a0d6-e8feacae886a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='content-5'])[9]</value>
      <webElementGuid>aacdaecb-7f64-42c6-b713-92ddee229a85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-691d779ccadf232d030c7f92-modal']/div/div/div[2]/form/div[5]/div[2]/div/div[5]/input</value>
      <webElementGuid>7bbaaeee-f43e-4947-a5a2-4effb4bfee66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/form/div[5]/div[2]/div/div[5]/input</value>
      <webElementGuid>42c18433-6dc0-4906-8964-da551daf63bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'content-5' and @type = 'radio' and @name = 'content']</value>
      <webElementGuid>949d29c6-30a5-4c2e-a726-646151ede2b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
