<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_active</name>
   <tag></tag>
   <elementGuidId>b08bcf50-a991-4cec-b1da-dc728f1e5c2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#status-act</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='status-act']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=radio[name=&quot;Active&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>328b1e40-a033-47fe-894f-8a23699b037a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>status-act</value>
      <webElementGuid>859db91e-d45f-4f46-b280-6dda5bbcc229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>021856d6-4d4e-49a4-b993-bbac5eaedc7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>94ce39ad-4fe2-4800-9d6a-c40586f922ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>922d42bc-1018-4ea1-960d-9bebfc7d8976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-4 h-4 text-blue-600 bg-gray-100 border-gray-300</value>
      <webElementGuid>205873d6-f283-4c64-8374-a92633c31ae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;status-act&quot;)</value>
      <webElementGuid>be3ea268-8ea9-4b91-88a8-40a88aa603ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='status-act']</value>
      <webElementGuid>29dbc159-6463-4bb4-bbd0-f51fe005d163</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='add-banner-modal']/div/div/div[2]/form/div[9]/div/div/input</value>
      <webElementGuid>8e460f6f-3c3e-41e6-a3b0-f39c5a28b326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/form/div[9]/div/div/input</value>
      <webElementGuid>f2cce7da-4968-4e9c-a269-272206eeab2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'status-act' and @type = 'radio' and @name = 'status']</value>
      <webElementGuid>8ca8e023-7852-49ba-8d7c-26090d345b78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
