<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_webpage</name>
   <tag></tag>
   <elementGuidId>33a37a54-424c-4962-9de0-ed7df340c9fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#type-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='type-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=radio[name=&quot;Webpage&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>543863f2-1bcb-4b68-9d5c-6baf2801468b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>type-2</value>
      <webElementGuid>c87fe5ec-9e18-4b5f-96f0-66d71267c705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>67fc5d4c-305a-41da-8758-fa206f303e5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>webpage</value>
      <webElementGuid>bbd6d1c9-28e6-42f3-9f89-25351144eeb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>type</value>
      <webElementGuid>ab46fa45-cd4b-4d89-a0a4-a40ffc04b5f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-4 h-4 text-blue-600 bg-gray-100 border-gray-300</value>
      <webElementGuid>e8062275-e30c-4e66-a30a-b9bfdc32a023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;type-2&quot;)</value>
      <webElementGuid>36427304-99c9-4f6b-9dbb-794568b2497d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='type-2']</value>
      <webElementGuid>cb100e7a-b4d4-4495-abc1-18c7fc091220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='add-banner-modal']/div/div/div[2]/form/div[4]/div/div[2]/input</value>
      <webElementGuid>4268d120-2c58-4625-8aec-39c22a159bdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/form/div[4]/div/div[2]/input</value>
      <webElementGuid>ac7fe963-82bd-45c9-9543-0744de255812</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'type-2' and @type = 'radio' and @name = 'type']</value>
      <webElementGuid>ab7fdc56-8771-4138-86d5-e8902f138068</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
