<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_slug</name>
   <tag></tag>
   <elementGuidId>a2875b50-fc8f-4290-82b5-b709833837c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#type-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='type-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=radio[name=&quot;Slug&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>79dd22a0-70d5-44a3-8406-08e628a0a374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>type-1</value>
      <webElementGuid>43f2a769-d451-4fea-95cd-0899d3d5b06e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>23cda899-c574-45fc-8da7-5e9aa08200cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>slug</value>
      <webElementGuid>cf8c199b-5d21-440d-a3ed-75a065f9d93d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>type</value>
      <webElementGuid>9fefd537-8018-4d3f-b10f-a4f53629776a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-4 h-4 text-blue-600 bg-gray-100 border-gray-300</value>
      <webElementGuid>1dce2a00-08c5-4fee-aed3-ebe2d2210371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;type-1&quot;)</value>
      <webElementGuid>320f0b3c-e3ad-498b-988b-9b0ec7bf8a5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='type-1']</value>
      <webElementGuid>e6576812-3375-4e58-87e7-b0c077408bf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='add-banner-modal']/div/div/div[2]/form/div[4]/div/div/input</value>
      <webElementGuid>00afd421-a51d-4ed5-a2b4-f162ffe41c9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/form/div[4]/div/div/input</value>
      <webElementGuid>d24b6bc4-c3a9-4b7d-bf19-7cb74fcebaa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'type-1' and @type = 'radio' and @name = 'type']</value>
      <webElementGuid>26d6d791-1ff7-4df3-86e5-b7df6165f40c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
