<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SaveEdit</name>
   <tag></tag>
   <elementGuidId>aa3a89ce-92c5-4f89-9961-0a58c0911c1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[8]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#edit-691ec225921b2b3d75029a13-modal > div.modal-dialog.modal-xs > div.modal-content > div.p-5 > form > div.py-8.pb-8.text-center > button.btn.btn-primary.w-24</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Save&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f025b0db-9cac-4ae9-9e8f-8f6274a8e156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>130da440-d7f1-4ce4-98df-558610ccc62f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary w-24</value>
      <webElementGuid>67fa52af-088b-492b-9e33-7b0f2d82a5ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>0f669242-131b-4c62-823c-68d8b7511084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-691ec225921b2b3d75029a13-modal&quot;)/div[@class=&quot;modal-dialog modal-xs&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;p-5&quot;]/form[1]/div[@class=&quot;py-8 pb-8 text-center&quot;]/button[@class=&quot;btn btn-primary w-24&quot;]</value>
      <webElementGuid>0a2c37ad-acd8-4e51-8032-0e1889b65ca7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[8]</value>
      <webElementGuid>5f51b1ab-fc10-4d9c-9ed9-1f1201b51e4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-691ec225921b2b3d75029a13-modal']/div/div/div[2]/form/div[7]/button[2]</value>
      <webElementGuid>b9e0d885-9ea2-4ee8-9fd5-dfe85c9d5e91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[7]/following::button[1]</value>
      <webElementGuid>2d4cda18-8f1e-48c6-affa-e9c2647f4a27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inactive'])[4]/following::button[2]</value>
      <webElementGuid>1767ba52-e6e4-4332-bae6-237a1449ac88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/form/div[7]/button[2]</value>
      <webElementGuid>2a5a6e31-9e53-4836-9a95-3044c22343b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>9102433a-59dd-4cae-b2c0-2a84e378a3db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
