<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Edit</name>
   <tag></tag>
   <elementGuidId>852f86f2-cbf6-4e78-8005-7e818f806307</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Redirect URI'])[2]/following::button[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.flex.items-center.text-success.mr-5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Edit&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4638562e-5752-47c7-b3b3-582a00d55353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center text-success mr-5</value>
      <webElementGuid>599f7e64-7274-48b1-955b-76582c025f88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tw-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>e0bd6e82-fe1d-47db-b209-d56c1d6e4980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tw-target</name>
      <type>Main</type>
      <value>#edit-63bbc13ec2445996b80ebabe-modal</value>
      <webElementGuid>338a63dd-5155-455d-946d-e3d8cef3cd97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    Edit
                                </value>
      <webElementGuid>4a1fcb50-4d60-474d-a9d6-b6efbd272445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;light&quot;]/body[@class=&quot;py-5 md:py-0&quot;]/div[@class=&quot;flex overflow-hidden&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;intro-y box p-5 mt-5&quot;]/div[@class=&quot;overflow-x-auto scrollbar-hidden&quot;]/table[@class=&quot;table my-8 sortable&quot;]/tbody[1]/tr[1]/td[7]/div[@class=&quot;flex justify-center&quot;]/button[@class=&quot;flex items-center text-success mr-5&quot;]</value>
      <webElementGuid>058d5934-dc86-4ea4-998f-73155dc27b07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Redirect URI'])[2]/following::button[1]</value>
      <webElementGuid>df0c417d-8d36-4d4f-b4f5-5ebf9dc5a09b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit OAuth Client'])[1]/preceding::button[1]</value>
      <webElementGuid>e6f71810-48d8-4959-a806-d33e22b688b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[4]/preceding::button[1]</value>
      <webElementGuid>4cfc5365-3e8c-4e9d-b926-42c0836f52fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit']/parent::*</value>
      <webElementGuid>9137e01d-cb3c-4d34-962e-26e5cacdc357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/div/button[2]</value>
      <webElementGuid>181bde42-f23a-4baa-b161-6a6f11713ead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '
                                    Edit
                                ' or . = '
                                    Edit
                                ')]</value>
      <webElementGuid>09e0d489-67f8-4d95-ba9d-fb5d20720fe0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
