<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>edit_URL</name>
   <tag></tag>
   <elementGuidId>91bf3c77-7492-490b-8d3d-86c6bfafbcb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='redirect_uri'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#edit-691ec225921b2b3d75029a13-modal > div.modal-dialog.modal-xs > div.modal-content > div.p-5 > form > div.mt-3 > input[name=&quot;redirect_uri&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;redirect_uri&quot;] >> nth=3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b4fd0e77-9fec-4061-af86-f6d7935a18a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>url</value>
      <webElementGuid>021c5471-ea26-4701-a319-26b09a819db1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>redirect_uri</value>
      <webElementGuid>63a4de1a-5989-4908-9e4a-02d87de6dec8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e75f9b84-1abc-4a0f-9089-2c763d74ff8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>http://mysite.com</value>
      <webElementGuid>6c5ee441-b860-4c72-b802-8c8fdae4ef64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-691ec225921b2b3d75029a13-modal&quot;)/div[@class=&quot;modal-dialog modal-xs&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;p-5&quot;]/form[1]/div[@class=&quot;mt-3&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>350eea03-8db0-4715-8c29-d9c88b5a9175</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='redirect_uri'])[4]</value>
      <webElementGuid>6581bf59-4e1c-463e-ae8e-787c659c8e13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-691ec225921b2b3d75029a13-modal']/div/div/div[2]/form/div[4]/input</value>
      <webElementGuid>6728988d-bb47-4ef6-ad59-294545617711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/form/div[4]/input</value>
      <webElementGuid>e01fc6cc-9457-4e0c-a690-fef007f0f93c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'url' and @name = 'redirect_uri']</value>
      <webElementGuid>d1877a6e-e2c0-4a47-8384-1beda1c78506</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
