<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>edit_phone number</name>
   <tag></tag>
   <elementGuidId>5d50c7cc-1cfe-430d-b158-dc04c666b141</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='phone_number1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#phone_number1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#phone_number1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>398f72c8-a0cb-40c5-80d1-8adea641719e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>a081b094-0354-4750-830f-c7f7066c44c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phone_number1</value>
      <webElementGuid>4ed6a5b5-7d1c-4a9d-aced-10d2ef0d1a78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phone_number</value>
      <webElementGuid>cd6c1928-3b16-41be-9578-4daeaa2d424f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>phone_number form-control</value>
      <webElementGuid>346c840b-a5d9-4174-8995-a34b08cd41e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>+6285293850000</value>
      <webElementGuid>3254db0d-4ab5-4ed4-9138-eafda03dd3d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2cf4dd10-0de8-41d6-913d-261870af664d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-intl-tel-input-id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f2aa0958-f91f-41f8-a02e-a084c0bde2b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phone_number1&quot;)</value>
      <webElementGuid>68763bb7-d847-44a2-bcc0-74cfebb41b59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='phone_number1']</value>
      <webElementGuid>bfba51b0-3034-4572-b0d6-6146d4eab687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-63bbc13ec2445996b80ebabe-modal']/div/div/div[2]/form/div[5]/div/input</value>
      <webElementGuid>3c8d6b58-4a88-4361-a7ad-ae68294b2e01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/form/div[5]/div/input</value>
      <webElementGuid>0bb5e85f-6d9a-49ae-94ef-69d3d0e7b975</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'phone_number1' and @name = 'phone_number']</value>
      <webElementGuid>f2a51056-00d1-4327-ad65-14e499a8dc80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
