<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_inactive</name>
   <tag></tag>
   <elementGuidId>64a0f642-d78e-47c9-a88c-c51510af7d81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='status-2'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#edit-691ec225921b2b3d75029a13-modal > div.modal-dialog.modal-xs > div.modal-content > div.p-5 > form > div.mt-3 > div.flex.gap-5 > div.flex.items-center > #status-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#status-2 >> nth=3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fe9475f2-85d5-494b-b721-341310a0ba74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>status-2</value>
      <webElementGuid>9d90b1aa-db9b-40f4-a294-8aaaf1cf0ccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>b28b0118-9d48-4c7c-ad16-1f04552b151d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>inactive</value>
      <webElementGuid>86864ca1-d293-498f-b559-3c7d394b1edc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>b92c00d3-b78a-404e-99ca-296fdc6fca5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-4 h-4 text-blue-600 bg-gray-100 border-gray-300</value>
      <webElementGuid>5334901c-9dc4-41ad-bc24-fa4ff0aa4d04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-691ec225921b2b3d75029a13-modal&quot;)/div[@class=&quot;modal-dialog modal-xs&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;p-5&quot;]/form[1]/div[@class=&quot;mt-3&quot;]/div[@class=&quot;flex gap-5&quot;]/div[@class=&quot;flex items-center&quot;]/input[@id=&quot;status-2&quot;]</value>
      <webElementGuid>ab1fd83a-dd8a-446f-a456-5170b2e00ae2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='status-2'])[4]</value>
      <webElementGuid>d6145102-5c47-434d-8bb3-007bd67a44e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-691ec225921b2b3d75029a13-modal']/div/div/div[2]/form/div[6]/div/div[2]/input</value>
      <webElementGuid>d4f547b3-dea5-461c-8375-05e08c3e254e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/form/div[6]/div/div[2]/input</value>
      <webElementGuid>74bf4eaf-35a9-479f-a1ee-02170720fc15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'status-2' and @type = 'radio' and @name = 'status']</value>
      <webElementGuid>89a32fb5-a2c7-426a-9d47-b1e9b6a9f3a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
