<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Status</name>
   <tag></tag>
   <elementGuidId>ee87833c-cdd6-424c-8a1f-f27c8a372cc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='status-1'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#add-oauth-client-modal > div.modal-dialog.modal-xs > div.modal-content > div.p-5 > form > div.mt-3 > div.flex.gap-5 > div.flex.items-center > #status-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#add-oauth-client-modal #status-1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2aa14d59-373d-40fb-bf34-bcaf70deff82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>status-1</value>
      <webElementGuid>20ff82b9-39f5-4079-b689-c11e8420e621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>b62686ca-95d9-4bec-ad5e-c7a178535e5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>6f830d58-8615-4ec7-b864-7b71d076de92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>91f38e9d-288e-4db0-bad1-3392031d1006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-4 h-4 text-blue-600 bg-gray-100 border-gray-300</value>
      <webElementGuid>4b5f6ea5-8f60-4403-916c-540c308f5ae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-oauth-client-modal&quot;)/div[@class=&quot;modal-dialog modal-xs&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;p-5&quot;]/form[1]/div[@class=&quot;mt-3&quot;]/div[@class=&quot;flex gap-5&quot;]/div[@class=&quot;flex items-center&quot;]/input[@id=&quot;status-1&quot;]</value>
      <webElementGuid>5855ef91-c7da-440c-9360-9b67bdc6d7d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='status-1'])[2]</value>
      <webElementGuid>082c56fb-4b52-40de-b2c3-a755454f4364</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='add-oauth-client-modal']/div/div/div[2]/form/div[6]/div/div/input</value>
      <webElementGuid>40fa6744-4235-4083-93e7-d16f5c7af9fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/form/div[6]/div/div/input</value>
      <webElementGuid>4bec5012-4ad9-4009-a1e9-c24c89afffac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'status-1' and @type = 'radio' and @name = 'status']</value>
      <webElementGuid>b9bf777f-ad5c-4ebc-8c2c-3d786ea0f8c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
