<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Review</name>
   <tag></tag>
   <elementGuidId>0dd2e95b-7c3b-451a-86d7-2bce43c45904</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#review-tab-677f75164e22a0755ab018fd > button.nav-link.w-full.py-2.active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[30]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;Review&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>28965670-cdc1-4532-851b-088a3561a899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link w-full py-2 active</value>
      <webElementGuid>b45acb61-2e27-4240-a71e-99658341c5ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tw-toggle</name>
      <type>Main</type>
      <value>pill</value>
      <webElementGuid>b8409d9d-e079-4484-b4c5-24ae8f2a1134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tw-target</name>
      <type>Main</type>
      <value>#review-content-677f75164e22a0755ab018fd</value>
      <webElementGuid>61880c56-700e-4180-80e7-33e074ec98ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f8659ced-b9ee-4a08-aad5-99ad8e0bb294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>b98f046b-5be0-4be0-8adc-f0946d0cf7df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>review-content</value>
      <webElementGuid>c40d027b-0a63-4444-a3a8-d1ea4eed235e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>701346ce-20a4-4c7d-8294-27eef2a18050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Review
                            </value>
      <webElementGuid>315748ed-e622-4bbf-a954-5ccbbb88364d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;review-tab-677f75164e22a0755ab018fd&quot;)/button[@class=&quot;nav-link w-full py-2 active&quot;]</value>
      <webElementGuid>6d8cadd9-32d6-4d63-9d98-7275a543d63f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[30]</value>
      <webElementGuid>4b381050-1b57-44d3-a749-591aec88c039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='review-tab-677f75164e22a0755ab018fd']/button</value>
      <webElementGuid>697a7e12-e306-4dd3-98cb-5848fe93908b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Conclusion'])[10]/following::button[1]</value>
      <webElementGuid>25002f87-8eef-4fd0-9d1d-76ad46697710</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transcript'])[10]/following::button[2]</value>
      <webElementGuid>8d327fe1-d2b8-4b2c-80e2-fc6312c6f1eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pingsan'])[10]/preceding::button[1]</value>
      <webElementGuid>c2a1f701-0631-493c-8a4a-888d4a29ce1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bicara meracau'])[8]/preceding::button[1]</value>
      <webElementGuid>3f04c0e1-3891-4584-81d3-6479a4d607ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/ul/li[3]/button</value>
      <webElementGuid>c719dd2e-246f-4283-8423-58c19a17f0b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
                                Review
                            ' or . = '
                                Review
                            ')]</value>
      <webElementGuid>9e098ba9-e981-4933-ab0b-6aa5e53e2ad1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
