<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Blue</name>
   <tag></tag>
   <elementGuidId>1aa1e170-1a4f-41b0-bb6b-a375d626c460</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tomselect-1-opt-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tomselect-1-opt-5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#tomselect-1-opt-5</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d42afc07-d5f4-4c00-8fdc-4ad55cfd25bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>blue</value>
      <webElementGuid>0374ba30-d9f7-442f-a509-a89e92e81c1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option active</value>
      <webElementGuid>2fcf9924-6a22-40ab-b238-c53f6bceb8d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>6e94010a-78cd-4967-90b6-0bef693b3b22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tomselect-1-opt-5</value>
      <webElementGuid>d7b8f253-280f-4508-9796-004d0004c764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>563dc980-1ad1-4c3d-a04c-43974f34d8be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Blue
                            </value>
      <webElementGuid>4e849e9f-9254-4878-aaff-0f89ad0c29da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tomselect-1-opt-5&quot;)</value>
      <webElementGuid>847598f9-8401-405d-9f5e-b8271f480449</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='tomselect-1-opt-5']</value>
      <webElementGuid>d8d43397-e817-4642-bb90-08f94853f25c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tomselect-1-ts-dropdown']/div[5]</value>
      <webElementGuid>283f361d-2247-4db0-be2c-6b1a2ab280d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Green'])[2]/following::div[1]</value>
      <webElementGuid>d08c99de-4314-455b-aaae-43b3426eee06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Safe'])[2]/following::div[2]</value>
      <webElementGuid>fbfe88ee-422a-4b8c-bd84-6eb5cbac59ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Normal'])[2]/preceding::div[1]</value>
      <webElementGuid>5db96456-d827-4de2-9c4c-2993d4e71308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inconclusive'])[2]/preceding::div[2]</value>
      <webElementGuid>d99dd248-2cd9-4991-8c01-f573f9f3928e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]</value>
      <webElementGuid>2cc9df81-ede7-495c-9b98-bed031e97471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'tomselect-1-opt-5' and (text() = '
                                Blue
                            ' or . = '
                                Blue
                            ')]</value>
      <webElementGuid>dca458a5-8b75-4c9f-9bd8-3a319831f539</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
