<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Baik</name>
   <tag></tag>
   <elementGuidId>224abbe1-e4c7-4cd0-9c85-0605ff9d04bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tomselect-2-opt-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tomselect-2-opt-4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#tomselect-2-opt-4</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>17a08ee4-7a67-45f1-b36e-419488404df9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>baik</value>
      <webElementGuid>78e6d1a5-ce54-4eaf-b6cc-67aa3247dc29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option active</value>
      <webElementGuid>2e6233c9-6f5b-4f90-8432-9cc4d763803f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>bd521a0d-4793-46c1-a40c-a89bb4be5c25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tomselect-2-opt-4</value>
      <webElementGuid>73858757-3871-4d69-8ca0-206f19e978bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a68b2a52-d817-4f0b-b6ef-634e9ae7de45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Baik
                            </value>
      <webElementGuid>2a88ffd8-72d2-4714-a5f4-9ce459cf17ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tomselect-2-opt-4&quot;)</value>
      <webElementGuid>c5584341-a355-42b7-8562-4f3c205bbe6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='tomselect-2-opt-4']</value>
      <webElementGuid>95f2d6c6-71dd-4223-b2a9-3b4a4274db14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tomselect-2-ts-dropdown']/div[4]</value>
      <webElementGuid>29385129-6135-4cc2-9224-f7b33c02dab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cukup'])[2]/following::div[1]</value>
      <webElementGuid>3c604d8b-ad2e-4db4-b73b-f6e6397e9a76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buruk'])[2]/following::div[2]</value>
      <webElementGuid>da4c104e-327f-4306-b558-e003c1fa9f7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sangat Baik'])[2]/preceding::div[1]</value>
      <webElementGuid>fefbd223-8482-4f2f-9b5a-3eda73b71f78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transcript'])[1]/preceding::div[3]</value>
      <webElementGuid>16f3fad8-5f5a-45c2-85df-fe7a16527abf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[2]/div[4]</value>
      <webElementGuid>3080c87c-bccc-4f33-aeeb-bc858fefa49b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'tomselect-2-opt-4' and (text() = '
                                Baik
                            ' or . = '
                                Baik
                            ')]</value>
      <webElementGuid>26209ddf-c50f-447d-8b38-87bc21c9bd11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
