<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_manage_doctor</name>
   <tag></tag>
   <elementGuidId>53f15484-58bd-4e80-91c2-29c356db5582</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='manage-doctor']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#manage-doctor</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;manage-doctor&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e9f52c83-56c6-4dd9-808a-ecf0becec6b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input appearance-none h-4 w-4 border border-gray-300 rounded-sm
                                                bg-white checked:bg-blue-600 checked:border-blue-600 focus:outline-none
                                                transition duration-200 mt-1 align-top bg-no-repeat bg-center
                                                bg-contain float-left mr-2 cursor-pointer permissions</value>
      <webElementGuid>89b894e1-3622-4c0e-bedd-fbb817b7dfc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f3b4d98f-73b7-4360-9d13-f6f4d4baa8a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>63823914ebb4b7451800a5c4</value>
      <webElementGuid>70f13272-da34-409a-87f8-d610dc7ccb88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>permissions[]</value>
      <webElementGuid>4033817b-e4b5-4026-9aed-b635991b2d4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>manage-doctor</value>
      <webElementGuid>109c13a6-ea85-4083-a542-e7be0eb07b52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;manage-doctor&quot;)</value>
      <webElementGuid>1a6704db-4fca-464a-aba2-59d1f671164d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='manage-doctor']</value>
      <webElementGuid>caffc4e3-3b53-42b8-913b-131920db66f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>5cd11e0a-cfed-4238-a5fa-71bda21adae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'permissions[]' and @id = 'manage-doctor']</value>
      <webElementGuid>6b72a7c9-bef7-4fcc-aad0-ad832933b8c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
