<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_is_remote</name>
   <tag></tag>
   <elementGuidId>74aff61d-741c-487d-a9fe-0bb0bd246443</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='yes-remote']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#yes-remote</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Yes&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ff329ab4-83ac-4798-a0d6-3d0079f7181f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>yes-remote</value>
      <webElementGuid>46815bdd-34e9-4cee-8e47-fcd4801adbc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>8f894b11-0d65-410d-8d75-460dc1ebf78a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>4b3068a8-cb92-4d6d-95b8-7093bb337d7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>is_remote</value>
      <webElementGuid>e2356312-8773-40ee-98aa-2a6e4f6eaced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>appearance-none h-4 w-4 border border-gray-300
                                            checked:bg-blue-600 checked:border-blue-600
                                            focus:outline-none mr-2 cursor-pointer</value>
      <webElementGuid>51f80d92-5a1f-4928-b887-e6fd43b19662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yes-remote&quot;)</value>
      <webElementGuid>bbc0b4cf-9119-4de8-87d4-b5fede10f073</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='yes-remote']</value>
      <webElementGuid>da60eed9-0c42-4d18-adea-e6184d83f3d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>d2759d4c-d18b-4a30-a26e-12673cf53457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'yes-remote' and @type = 'radio' and @name = 'is_remote']</value>
      <webElementGuid>c9ac3095-b2c0-4dec-ac69-58bc60c33481</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
