<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_manage-user-backoffice</name>
   <tag></tag>
   <elementGuidId>28813964-192b-44bc-b409-1502674c892e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='manage-user-backoffice']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#manage-user-backoffice</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;manage-user-backoffice&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>28912062-15b7-4d77-8751-6b74fcc216b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input appearance-none h-4 w-4 border border-gray-300 rounded-sm
                                                bg-white checked:bg-blue-600 checked:border-blue-600 focus:outline-none
                                                transition duration-200 mt-1 align-top bg-no-repeat bg-center
                                                bg-contain float-left mr-2 cursor-pointer permissions</value>
      <webElementGuid>62d3d0de-ac9a-41d2-931a-f6336a74d2f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7939e879-2522-41b7-86bd-e83fe8ce36cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>63823914ebb4b7451800a5ce</value>
      <webElementGuid>d7a09e36-717c-41ad-a0c5-8313e3a07374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>permissions[]</value>
      <webElementGuid>054943ae-1b96-4f79-8841-9eaca10f1a5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>manage-user-backoffice</value>
      <webElementGuid>1d594ef7-4373-42a1-bb3d-6d3a7c2ebd32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;manage-user-backoffice&quot;)</value>
      <webElementGuid>648b24f8-97b6-4a3c-b4f9-de5dcb484103</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='manage-user-backoffice']</value>
      <webElementGuid>19054933-06a0-45a6-9dd1-b7fd87fe038f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/input</value>
      <webElementGuid>ff435cf4-6652-4ffc-990c-9ddd958d4a8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'permissions[]' and @id = 'manage-user-backoffice']</value>
      <webElementGuid>f3b83505-9659-4b8b-8656-a81f8367ad31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
