<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_manage-banner</name>
   <tag></tag>
   <elementGuidId>3280baf6-3733-458b-9c93-02c1901e4cc0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='manage-banner']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#manage-banner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;manage-banner&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>32851306-87ca-4e26-9800-804d7c6bcbf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input appearance-none h-4 w-4 border border-gray-300 rounded-sm
                                                bg-white checked:bg-blue-600 checked:border-blue-600 focus:outline-none
                                                transition duration-200 mt-1 align-top bg-no-repeat bg-center
                                                bg-contain float-left mr-2 cursor-pointer permissions</value>
      <webElementGuid>dbfbb5fe-8ea4-4bf0-9939-066af12555f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>51ccaa1d-8788-46ac-b274-a5a7b9002f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>646b25c7db300b56577fcff1</value>
      <webElementGuid>e52657f4-a049-43f7-92b4-7ef274b86081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>permissions[]</value>
      <webElementGuid>191c7da3-ccd3-4ebe-b748-fdebdb72adad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>manage-banner</value>
      <webElementGuid>526be7ec-cb18-46d3-8a69-87fb865988e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;manage-banner&quot;)</value>
      <webElementGuid>616bfc35-9156-4055-8e85-bb0c827bdf62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='manage-banner']</value>
      <webElementGuid>ee135a8b-86e2-4078-a059-6a3c337b149a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/input</value>
      <webElementGuid>da171345-6f39-4ebf-b821-f5108d5a08fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'permissions[]' and @id = 'manage-banner']</value>
      <webElementGuid>13a81cc6-28f8-46ef-ac30-f064355e6762</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
