<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cancel</name>
   <tag></tag>
   <elementGuidId>613a6e9b-8d39-4621-82db-91ec9d9a5044</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[10]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Cancel&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>577b7ab3-4e61-4adc-bdb9-1fb4733c01b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tw-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>ac784840-e59d-4a28-afb4-bbf55bff1c8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f14c2ec8-6d82-4315-b2f6-bf71839caf24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-gray-500 bg-white hover:bg-gray-100 focus:ring-4 focus:outline-none
                            focus:ring-gray-200 rounded-lg border border-gray-200 text-sm font-medium
                            px-5 py-2.5 hover:text-gray-900 focus:z-10</value>
      <webElementGuid>e8976e77-6201-436b-904f-6e93e3ac301e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Cancel
                    </value>
      <webElementGuid>82af4fc8-f3ab-4960-aea3-88627f86b2d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;delete-692415f5b4e01485740f85d2-modal&quot;)/div[@class=&quot;modal-dialog modal-md&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;p-6 text-center&quot;]/form[1]/button[@class=&quot;text-gray-500 bg-white hover:bg-gray-100 focus:ring-4 focus:outline-none
                            focus:ring-gray-200 rounded-lg border border-gray-200 text-sm font-medium
                            px-5 py-2.5 hover:text-gray-900 focus:z-10&quot;]</value>
      <webElementGuid>d21f421d-3f8b-4c18-b6e0-fc12940e6ecf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[10]</value>
      <webElementGuid>61bc7374-fe4b-4d30-9f25-6c021637dbcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='delete-692415f5b4e01485740f85d2-modal']/div/div/div/form/button</value>
      <webElementGuid>56580d9e-5ed8-474a-8a1f-ac6123fcb117</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure you want to delete testingg123'])[1]/following::button[1]</value>
      <webElementGuid>1415f081-7de1-4a50-b3b1-83a10b680c38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::button[1]</value>
      <webElementGuid>b22d7b8a-1425-4c97-8564-ae45e2582d47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[10]/preceding::button[1]</value>
      <webElementGuid>3a0975ef-2dd3-4111-96d1-868a9dd9f173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/form/button</value>
      <webElementGuid>5a02d230-a1fc-4f1d-a1b5-5be1071632c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
                        Cancel
                    ' or . = '
                        Cancel
                    ')]</value>
      <webElementGuid>54b4573b-b0af-48d3-b1b9-6819a75e5abf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
