<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Categories</name>
   <tag></tag>
   <elementGuidId>74bfdbbb-7d74-4b9e-8d7f-9d1ebce4e0ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='COVID-19']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#COVID-19</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;COVID-19&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3f53f3d9-cfb9-4555-92ec-ae0f47fb0c6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input
                                    appearance-none h-4 w-4 border border-gray-300
                                    rounded-sm bg-white checked:bg-blue-600
                                    checked:border-blue-600 mt-1 mr-2 cursor-pointer</value>
      <webElementGuid>a43118b8-5f4f-4ee4-a35a-a9cfad44daef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c29308a1-061d-4e5a-becf-1499bdbc7746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>6373121b365d58e6f5539c79</value>
      <webElementGuid>1505967e-5ce9-443d-9c35-06b66b4646f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>categories[]</value>
      <webElementGuid>254333f3-cb4e-4a33-9c9e-728f19aebf94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>COVID-19</value>
      <webElementGuid>81f299ee-55a7-43b9-99ee-5d7f8f4c21ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;COVID-19&quot;)</value>
      <webElementGuid>7aa8a264-b5ae-4a11-802d-c8bc026147fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='COVID-19']</value>
      <webElementGuid>655fbf8c-a8da-4eec-9d77-cc06e80fece3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>69af79a5-7fcb-4fc0-b290-aef498cacb75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'categories[]' and @id = 'COVID-19']</value>
      <webElementGuid>25ff7055-8707-4893-9e4d-f2a7731a0629</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
