<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Base Price</name>
   <tag></tag>
   <elementGuidId>878e682a-18f1-4679-91dd-58b95c554a45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='base_price']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;base_price&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;base_price&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6bc5c88a-1f52-4388-9fba-6665c3f1ed5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2c8b39a6-46ed-4ddb-8b92-e22e8a24b8aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>base_price</value>
      <webElementGuid>547b658e-a6ab-469a-9797-90c0d7f93477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control pricing</value>
      <webElementGuid>fddef539-fd10-4d24-ae49-09d37bb3b84a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;light&quot;]/body[@class=&quot;py-5 md:py-0&quot;]/div[@class=&quot;flex overflow-hidden&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;col-span-12 lg:col-span-8 2xl:col-span-9&quot;]/div[@class=&quot;intro-y box lg:mt-5&quot;]/div[@class=&quot;p-5&quot;]/form[@class=&quot;form-medicine&quot;]/div[@class=&quot;grid grid-cols-3 gap-4&quot;]/div[@class=&quot;mt-3&quot;]/input[@class=&quot;form-control pricing&quot;]</value>
      <webElementGuid>8ca2b3d9-95d3-4c04-9c84-c17af75f586a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='base_price']</value>
      <webElementGuid>57d9c6b5-d42e-4be0-acc0-1a64a5bf75b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>e545b6f2-4591-4273-95de-6fdedf7c5d45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'base_price']</value>
      <webElementGuid>5e543035-f540-48ad-ac6c-8f2deda39e82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
