<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Selling Unit</name>
   <tag></tag>
   <elementGuidId>81db5d08-518e-499b-a5c8-922c3ebc4622</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='selling_unit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;selling_unit&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;selling_unit&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>36534bdb-965b-4216-bf15-950f56cb2d28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6c5b3407-d335-4edf-9d96-588808f1b19a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>selling_unit</value>
      <webElementGuid>ac6f5d9f-55da-45b6-9152-adeefa1e709e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3b248671-c8a5-4fd3-9976-06ef60fa9810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;light&quot;]/body[@class=&quot;py-5 md:py-0&quot;]/div[@class=&quot;flex overflow-hidden&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;col-span-12 lg:col-span-8 2xl:col-span-9&quot;]/div[@class=&quot;intro-y box lg:mt-5&quot;]/div[@class=&quot;p-5&quot;]/form[@class=&quot;form-medicine&quot;]/div[@class=&quot;grid grid-cols-3 gap-4&quot;]/div[@class=&quot;mt-3&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>1677c2bd-32bb-4233-954a-2e8c99c16c8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='selling_unit']</value>
      <webElementGuid>f61c1674-9c26-49d0-9117-4373f8cb20a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/input</value>
      <webElementGuid>0e5b1617-9212-4891-aae6-deafa4a3c32a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'selling_unit']</value>
      <webElementGuid>26e1a59d-9c49-43a3-aa9e-223db1662f85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
