<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>search_composition</name>
   <tag></tag>
   <elementGuidId>e1d1eec6-ad2a-4b3c-ba8d-3d73f96530a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='medicine_composition']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;medicine_composition&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Composition&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bb98a315-93fc-4567-99c2-841d0e0df209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>medicine_composition</value>
      <webElementGuid>b9836916-509a-4ce8-a87f-d1663c6bb05f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>978023c6-cd30-4e62-8fa8-e641945ec148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>adf09a1d-29dc-4a57-8f1d-3d4fea5ad9c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Composition</value>
      <webElementGuid>3e1431b5-0b75-4442-96a3-bbfcaad2ba41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Diclofenac</value>
      <webElementGuid>34f84d7b-ca9c-4e47-a5e5-e71412fae717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;advanced_search&quot;)/div[@class=&quot;text-slate-600 leading-relaxed&quot;]/form[1]/div[@class=&quot;grid grid-cols-12 gap-4 mt-5&quot;]/div[@class=&quot;col-span-12 sm:col-span-6 xl:col-span-2&quot;]/div[@class=&quot;input-group&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>3307fbdd-d542-4351-95c4-34adf41766fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='medicine_composition']</value>
      <webElementGuid>dd0326a9-f7d2-4751-b68b-40ca86ac8e0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='advanced_search']/div/form/div/div[4]/div/input</value>
      <webElementGuid>e6e53cd0-0c1d-49e4-acad-d73739214b1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>e6ead09a-f246-4b99-bf49-b18b5db55a3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'medicine_composition' and @type = 'text' and @placeholder = 'Composition']</value>
      <webElementGuid>367a6740-bf65-4afe-aebb-41b7bd26bfde</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
