<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Edit</name>
   <tag></tag>
   <elementGuidId>848be7b4-002d-4c2f-81df-65890568531d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='tbl-doctor']/tr/td[8]/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.flex.items-center.text-success.mr-5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;1 68e4cd45af41d451d606a553 DoctorID Dr Semakin di Devan Dokter Umum Rp. 1,000 Rp. 1,000 4 Edit Delete&quot;i] >> internal:role=button >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c39bfe11-8f60-4e1d-9606-1f214c9606f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center text-success mr-5</value>
      <webElementGuid>99eb9fbf-7bab-453f-96c0-8d517d790390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tw-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>5dfa78e1-fddf-4a73-b4f6-dfaccf41b145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tw-target</name>
      <type>Main</type>
      <value>#edit-68e4cd45af41d451d606a553-modal</value>
      <webElementGuid>8e8e1ea8-cb45-4248-81b3-6bfd6ca78d4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                            Edit
                                        </value>
      <webElementGuid>c77a6182-7194-4ce8-b878-eccfc533ff7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbl-doctor&quot;)/tr[1]/td[8]/div[@class=&quot;flex justify-center&quot;]/button[@class=&quot;flex items-center text-success mr-5&quot;]</value>
      <webElementGuid>f186b1f9-1eac-418f-865d-69f09e6266fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tbl-doctor']/tr/td[8]/div/button</value>
      <webElementGuid>8842732a-ebbe-4741-a534-6da8a7e5c679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp. 1,000'])[1]/following::button[1]</value>
      <webElementGuid>4868377b-13e9-4ade-bd76-8d44ab90b76f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Specialty'])[2]/preceding::button[1]</value>
      <webElementGuid>458a61a3-2fba-4be4-b2b7-255e1d2fa113</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit']/parent::*</value>
      <webElementGuid>a921cc02-bde3-4aa5-b2a5-b7e2a29fd0a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/div/button</value>
      <webElementGuid>cda19a94-b881-489a-bace-866a7db5c70b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '
                                            Edit
                                        ' or . = '
                                            Edit
                                        ')]</value>
      <webElementGuid>ee4e29d2-2d95-4ebd-a277-b3db6fa7e2e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
