<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Comission ke AICare Video Price_doctorprice_video</name>
   <tag></tag>
   <elementGuidId>f0235e5c-8b96-46f9-ab63-01ef0133c6aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='doctorprice_video_690afa405f874c06f2063f53']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#doctorprice_video_690afa405f874c06f2063f53</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>form >> internal:has-text=&quot;Specialty Dokter Umum Doctor's Name dr Juno Test Position Chat Video Call Chat P&quot;i >> input[name=&quot;doctorprice_video&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5a52a28c-5ee4-4e38-b27c-ab7b0683ce67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c62332c4-8df3-4893-be67-bd012287c82c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>doctorprice_video</value>
      <webElementGuid>27fe80a6-a26c-4c18-a496-da58bc41bd2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>doctorprice_video_690afa405f874c06f2063f53</value>
      <webElementGuid>73ab8523-ce3d-4a2e-ac47-f701b35c1c12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control pricing-video</value>
      <webElementGuid>e7971d34-a6a8-4453-87ef-1e320518a59a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1ecbe53c-a0d2-4d4d-891b-a4c6ca4b904c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;doctorprice_video_690afa405f874c06f2063f53&quot;)</value>
      <webElementGuid>79095223-613e-486b-8be9-02a809b0721f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='doctorprice_video_690afa405f874c06f2063f53']</value>
      <webElementGuid>164b1ba4-04b3-4f39-a0e4-d048efe3c051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-690afa405f874c06f2063f53-modal']/div/div/div[2]/form/div[5]/div[4]/div[2]/input</value>
      <webElementGuid>46665b71-56e0-4324-9bef-80ab3c41b261</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/form/div[5]/div[4]/div[2]/input</value>
      <webElementGuid>e571f273-412a-433a-b380-9fa83c4638b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'doctorprice_video' and @id = 'doctorprice_video_690afa405f874c06f2063f53']</value>
      <webElementGuid>effdde2c-2c07-4125-af3b-8f1782ae7773</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
