<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_IDR_normalprice_chat</name>
   <tag></tag>
   <elementGuidId>13f4f0bb-f4e9-4ff8-b430-fd493923bfcc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='normalprice_chat_690afa405f874c06f2063f53']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#normalprice_chat_690afa405f874c06f2063f53</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>form >> internal:has-text=&quot;Specialty Dokter Umum Doctor's Name dr Juno Test Position Chat Video Call Chat P&quot;i >> input[name=&quot;normalprice_chat&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fae58f20-6398-44ac-b1c4-dc2ca1e9bf98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e8096dea-81c5-4ea8-b7e9-ae9dcb2bf479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>normalprice_chat</value>
      <webElementGuid>1eb8b5a4-ff0f-4d99-907c-55594750c7c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>normalprice_chat_690afa405f874c06f2063f53</value>
      <webElementGuid>f6f18410-ef25-4aad-ac91-b0bf05dea2f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control pricing-chat</value>
      <webElementGuid>47cf5e48-995b-4379-8766-821d0ddac33c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3aed20ee-3ecb-437d-99a1-ae7bfdafb4cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;normalprice_chat_690afa405f874c06f2063f53&quot;)</value>
      <webElementGuid>97abf9bf-590f-4bf1-b0a8-7fdee5089173</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='normalprice_chat_690afa405f874c06f2063f53']</value>
      <webElementGuid>1f8755b8-dc4e-4c09-aab0-6a2b84f93dd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-690afa405f874c06f2063f53-modal']/div/div/div[2]/form/div[5]/div/div[2]/input</value>
      <webElementGuid>d5c67769-2a6a-4cb1-80ce-c4cb2668ae02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/form/div[5]/div/div[2]/input</value>
      <webElementGuid>6f9bf427-2a18-4802-bbdb-a6aac01c4127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'normalprice_chat' and @id = 'normalprice_chat_690afa405f874c06f2063f53']</value>
      <webElementGuid>034033e4-2dc0-408e-ad5c-3c9565e2e30d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
