<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_IDR_normalprice_video</name>
   <tag></tag>
   <elementGuidId>bbbc9924-a77e-4881-92a8-27fabd3504af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='normalprice_video_690afa405f874c06f2063f53']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#normalprice_video_690afa405f874c06f2063f53</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>form >> internal:has-text=&quot;Specialty Dokter Umum Doctor's Name dr Juno Test Position Chat Video Call Chat P&quot;i >> input[name=&quot;normalprice_video&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>66e245f0-eb8f-49ae-b6bc-0c789b5852d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4662b824-b401-46ec-9803-df7239ac3bd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>normalprice_video</value>
      <webElementGuid>60aaafb3-462e-4221-8594-8dfa1b9644d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>normalprice_video_690afa405f874c06f2063f53</value>
      <webElementGuid>8b2ee98c-f3bb-48d6-ae12-fc8565401906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control pricing-video</value>
      <webElementGuid>6cc280d2-cf35-4794-8ca5-ef101a650137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>be2da2ca-8ab7-4fbf-8c15-91b558b07ccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;normalprice_video_690afa405f874c06f2063f53&quot;)</value>
      <webElementGuid>66ae4c10-2268-46eb-92bb-aa5806111c42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='normalprice_video_690afa405f874c06f2063f53']</value>
      <webElementGuid>110f83b3-14ce-4fc3-91fc-5ae5108d4b36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-690afa405f874c06f2063f53-modal']/div/div/div[2]/form/div[5]/div[3]/div[2]/input</value>
      <webElementGuid>bacecdbe-8073-4d25-9f0f-f7a85634f65a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/form/div[5]/div[3]/div[2]/input</value>
      <webElementGuid>a60fc714-9a69-4e2b-a7ae-019fa7aa5252</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'normalprice_video' and @id = 'normalprice_video_690afa405f874c06f2063f53']</value>
      <webElementGuid>148f2292-dde8-40a6-8abc-c30125504227</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
