<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Comission ke AICare Chat Price_doctorprice_chat</name>
   <tag></tag>
   <elementGuidId>9d5fd0d4-32b9-4d77-89af-b627545e7b2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='doctorprice_chat_690afa405f874c06f2063f53']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#doctorprice_chat_690afa405f874c06f2063f53</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>form >> internal:has-text=&quot;Specialty Dokter Umum Doctor's Name dr Juno Test Position Chat Video Call Chat P&quot;i >> input[name=&quot;doctorprice_chat&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b27a438a-3c99-42aa-abd0-be60083ba2e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c130e896-a810-43f1-894d-aaef7392f2b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>doctorprice_chat</value>
      <webElementGuid>0584bbeb-e8d2-4a84-9f60-8e2390ea1d73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>doctorprice_chat_690afa405f874c06f2063f53</value>
      <webElementGuid>8704c456-62ab-4991-8c9f-b43255f2d141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control pricing-chat</value>
      <webElementGuid>aa46c289-d9e4-46ea-a770-577e3db4b36c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ff611227-d9bb-40e4-a8ce-25ae2c3fefbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;doctorprice_chat_690afa405f874c06f2063f53&quot;)</value>
      <webElementGuid>4ed2e63f-7a7d-4669-aeb2-571c17a1e06f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='doctorprice_chat_690afa405f874c06f2063f53']</value>
      <webElementGuid>104d33f9-4e56-4e38-8327-3655427a0581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-690afa405f874c06f2063f53-modal']/div/div/div[2]/form/div[5]/div[2]/div[2]/input</value>
      <webElementGuid>fdfabf68-3f4a-4236-b1a4-b848fbb23dc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/form/div[5]/div[2]/div[2]/input</value>
      <webElementGuid>4b006de0-af26-4ef7-870a-3c954b73ae9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'doctorprice_chat' and @id = 'doctorprice_chat_690afa405f874c06f2063f53']</value>
      <webElementGuid>218ca3ec-aa2d-401d-b2c9-d49832c214b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
