<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_panah kiri</name>
   <tag></tag>
   <elementGuidId>cd6293a9-9b64-40d3-89b2-bb2098346282</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.fc-prev-button.fc-button.fc-button-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Previous week&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>954364bc-d75f-489f-a64a-f1ec68a7fe9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3a735334-931a-466a-ba01-f18da4126b32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Previous week</value>
      <webElementGuid>cad4339e-58ef-4d8e-a0a5-ef3fef60bec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-pressed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c9e79c3a-92f9-4540-9f08-a1a9d1a14f58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fc-prev-button fc-button fc-button-primary</value>
      <webElementGuid>258d9b3c-9c17-4cca-8868-469dbb3a69cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calendar_dashboard&quot;)/div[@class=&quot;fc-header-toolbar fc-toolbar&quot;]/div[@class=&quot;fc-toolbar-chunk&quot;]/div[@class=&quot;fc-button-group&quot;]/button[@class=&quot;fc-prev-button fc-button fc-button-primary&quot;]</value>
      <webElementGuid>083da5c7-8baa-400d-a958-ee31b509acaf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>32648aaa-e5e9-44c7-a053-b2fa2005fd73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='calendar_dashboard']/div/div[3]/div/button</value>
      <webElementGuid>df47e93a-8f0f-4894-bf99-dcad6a978a4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='today'])[1]/following::button[1]</value>
      <webElementGuid>5ae2bc47-d15f-4cff-a98d-33434ed77a97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time'])[1]/preceding::button[2]</value>
      <webElementGuid>86eb9067-440e-4494-bbfb-5fc32c805656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event'])[1]/preceding::button[2]</value>
      <webElementGuid>255526be-1818-4c6f-8d09-6c93ae10c8a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>0c197df3-ffbc-465d-a41b-123db25784be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @title = 'Previous week']</value>
      <webElementGuid>761b756f-771c-47a1-aa30-056e41feb345</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
