<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chart_demografi</name>
   <tag></tag>
   <elementGuidId>ba9cecf0-ec99-48e5-9cb9-14c41c1f1001</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//canvas[@id='symptom-checker-user-demographic-chart']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#symptom-checker-user-demographic-chart</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#symptom-checker-user-demographic-chart</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>26b2dedf-da86-441d-a25c-55900ef9412f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>symptom-checker-user-demographic-chart</value>
      <webElementGuid>c5d7c80f-1cd3-43a7-a747-10c4742dfe32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-5 -mb-6</value>
      <webElementGuid>cdbba422-89dc-4cee-917a-0ce1ae1c3241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>787</value>
      <webElementGuid>bdbae81a-8170-4d5a-8a62-89bb79fd1f24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>279</value>
      <webElementGuid>883ad277-fab6-4d86-bf69-ac89811e021e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;symptom-checker-user-demographic-chart&quot;)</value>
      <webElementGuid>fa825fa9-bb5a-4abd-a1cb-e1bdac821b91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//canvas[@id='symptom-checker-user-demographic-chart']</value>
      <webElementGuid>3ab52246-8865-4e81-8346-2f452ef05d89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/canvas</value>
      <webElementGuid>6e747a87-22df-4e0b-aadd-cb81603ffba0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//canvas[@id = 'symptom-checker-user-demographic-chart']</value>
      <webElementGuid>5bbc3fbb-7fb6-40db-a495-eb25f69499ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
