<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chart_user</name>
   <tag></tag>
   <elementGuidId>e28beb00-5647-4849-9c9c-43a0758cb6be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//canvas[@id='katherine-gpt-event-chart']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#katherine-gpt-event-chart</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#katherine-gpt-event-chart</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>27ea61d7-c354-4ceb-a65c-d49d76722070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>katherine-gpt-event-chart</value>
      <webElementGuid>089622ab-a860-4bef-b245-931cc61355de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-5 -mb-6</value>
      <webElementGuid>ff379ae3-0995-4c8f-9567-6c7de78f2bf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>550</value>
      <webElementGuid>48df2462-eb22-421b-9f1b-1d8bca6ecf5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>275</value>
      <webElementGuid>13d19db0-1799-41e5-8623-7e98099aaaae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;katherine-gpt-event-chart&quot;)</value>
      <webElementGuid>b92cf333-cc66-44cb-acbc-4738868fd33c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//canvas[@id='katherine-gpt-event-chart']</value>
      <webElementGuid>1ad8a385-b64d-4ef0-a54b-7839f39f2d25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/canvas</value>
      <webElementGuid>c0b50273-f86a-43e3-9c72-55eb53994d92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//canvas[@id = 'katherine-gpt-event-chart']</value>
      <webElementGuid>f4085cf7-bf91-465d-a959-7985a0a798f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
