<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_regulation</name>
   <tag></tag>
   <elementGuidId>dd549ebf-d00c-4d23-a1cd-6b6bcbc0f595</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tomselect-1-ts-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tomselect-1-ts-control']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#tomselect-1-ts-control</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>803534f9-7af3-40ef-bc20-b25be2354a01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ts-control</value>
      <webElementGuid>ff2353ba-d8dc-4165-bcd6-e51896199b1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>3ae1fd5d-ac30-4f66-bc12-673dcdef7a12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>4507fb1f-3160-43a4-8a16-c61bbd52e3e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9cc080d2-6a1f-4b2d-8983-d457ad3ff10c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>tomselect-1-ts-dropdown</value>
      <webElementGuid>6e5f3289-75af-403a-b822-186787b35c5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tomselect-1-ts-control</value>
      <webElementGuid>879b7a95-268e-40af-9ace-61a3b785a536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a631865f-a09d-4499-9882-bad16d31bbc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>tomselect-1-opt-2</value>
      <webElementGuid>4ba548e3-19c1-4185-9e68-f152c28633de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>IDI</value>
      <webElementGuid>13622c54-fe2d-46b6-a322-7d59ef477de4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tomselect-1-ts-control&quot;)</value>
      <webElementGuid>f931c8b6-6168-4259-8745-4343ff7d2888</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='tomselect-1-ts-control']</value>
      <webElementGuid>47b511ec-23df-44d0-86a0-3fd972b2f9d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filter_regulation_symptom_checker']/div/div</value>
      <webElementGuid>28a51f6e-856d-47df-8ee4-8d120b039305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regulation'])[1]/following::div[3]</value>
      <webElementGuid>3a865041-7de8-4552-b548-a33ff9420f6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rule Analysis as of 17 Nov 2025'])[1]/following::div[6]</value>
      <webElementGuid>f10272a5-e5f8-41ad-b707-86872ba596d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WHO'])[2]/preceding::div[3]</value>
      <webElementGuid>5a1c27fa-5020-4a8c-bf16-1eb36bc8deac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div[2]/div/div</value>
      <webElementGuid>6d4e3957-b804-42bc-a02c-4ee52426c803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'tomselect-1-ts-control' and (text() = 'IDI' or . = 'IDI')]</value>
      <webElementGuid>935c328e-20ff-457d-aa65-8c91e98a491c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
