<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cancel</name>
   <tag></tag>
   <elementGuidId>62975543-697b-4518-a483-f2217c65cff9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[54]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.py-5.pb-8.text-end > button.btn.btn-outline-primary.w-24.mr-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Cancel&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>850d0f8f-075f-48f7-9b58-dc92c1493ff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4c29482e-6e8c-45d5-838a-5367e0f5096e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tw-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>d8acb316-7a1e-4e9e-aefa-97d7c1a694af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-outline-primary w-24 mr-1</value>
      <webElementGuid>dbf8c715-3001-425b-b726-7030fb473a45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Cancel
                        </value>
      <webElementGuid>ed3c3290-7d19-4045-9f45-b7da0a41640c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-doctor-modal&quot;)/div[@class=&quot;modal-dialog modal-xl&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;px-5&quot;]/form[@class=&quot;form-doctor&quot;]/div[@class=&quot;py-5 pb-8 text-end&quot;]/button[@class=&quot;btn btn-outline-primary w-24 mr-1&quot;]</value>
      <webElementGuid>ebb0e635-fe68-482f-9e6c-5b9c1197a857</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[54]</value>
      <webElementGuid>c8260f4a-3e11-4bb9-ac8d-c41c16ede983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='add-doctor-modal']/div/div/div/form/div[29]/button</value>
      <webElementGuid>9525cd57-8ed7-4a0f-9fa4-5eb4db0d1193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No file chosen'])[2]/following::button[1]</value>
      <webElementGuid>9c30aa47-26db-43a5-a1b1-670affc04f7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[1]/preceding::button[1]</value>
      <webElementGuid>19c23ec5-6f46-4fb3-9322-9ecd234299a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[29]/button</value>
      <webElementGuid>b2cd1de3-967b-43e6-946c-26e9bec1d535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
                            Cancel
                        ' or . = '
                            Cancel
                        ')]</value>
      <webElementGuid>d62c5036-869b-4ce6-84ed-6444846e83c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
