<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SIP Number Expiration Date</name>
   <tag></tag>
   <elementGuidId>1cffaf1b-c2a2-43cc-a0ad-71780ed4c9bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='sip_exp'])[11]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>form.form-doctor > div.grid.grid-cols-2.gap-4 > div.col-span-1 > input[name=&quot;sip_exp&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#add-doctor-modal input[name=&quot;sip_exp&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2a42c91f-dd7a-4226-8233-1d29cfd1c104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>b471333a-b99a-447d-a2c3-ee310b4ec587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sip_exp</value>
      <webElementGuid>79f1df31-3868-4a15-8e7e-eca07d89e500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3ad5f35a-c145-4fc3-8e05-6d5e4e179991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-doctor-modal&quot;)/div[@class=&quot;modal-dialog modal-xl&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;px-5&quot;]/form[@class=&quot;form-doctor&quot;]/div[@class=&quot;grid grid-cols-2 gap-4&quot;]/div[@class=&quot;col-span-1&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>5721e421-cf78-4307-8bd0-ac3b551d4dd5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='sip_exp'])[11]</value>
      <webElementGuid>0c23f65c-5676-41dd-b837-8064e8abbf7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='add-doctor-modal']/div/div/div/form/div[27]/div[2]/input</value>
      <webElementGuid>30350c00-9e03-4564-940d-589f94f625b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[27]/div[2]/input</value>
      <webElementGuid>8b93f2e8-6736-406c-af4d-3f0d92a78033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @name = 'sip_exp']</value>
      <webElementGuid>ca713989-aefa-4141-a555-24317eb3ef79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
