<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zip Code</name>
   <tag></tag>
   <elementGuidId>b074acfc-ce22-4c85-bb4d-570ed72b2704</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='zip_code'])[11]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>form.form-doctor > div.grid.grid-cols-2.gap-4 > div.col-span-1 > input[name=&quot;zip_code&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#add-doctor-modal input[name=&quot;zip_code&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8bc75a33-975a-45c2-b768-ff4efe95797b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f1de0aed-afd7-405d-a96a-65c36b04c89c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>zip_code</value>
      <webElementGuid>3c37a715-c077-418c-88c1-d1f244fca065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2e2e7207-ee7a-432a-8e9c-cc04b4b9301f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]{5}</value>
      <webElementGuid>5fccb1f1-2dc6-43b1-b1ae-a403f4d99007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Zip Code Must Contain 5 Digits</value>
      <webElementGuid>19c400fa-a257-43c1-9f09-53b6b176b1bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-doctor-modal&quot;)/div[@class=&quot;modal-dialog modal-xl&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;px-5&quot;]/form[@class=&quot;form-doctor&quot;]/div[@class=&quot;grid grid-cols-2 gap-4&quot;]/div[@class=&quot;col-span-1&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>96e7040d-6104-4a18-9c74-e255f1a9e6d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='zip_code'])[11]</value>
      <webElementGuid>ed7c21ee-0f90-4389-b5ab-c1b1bc78d4e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='add-doctor-modal']/div/div/div/form/div[21]/div[2]/input</value>
      <webElementGuid>e259520b-9a14-464c-8b5d-f0dc689cb815</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[21]/div[2]/input</value>
      <webElementGuid>8f1d5ee4-a764-4d2c-a6e7-6dad39d19573</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'zip_code' and @title = 'Zip Code Must Contain 5 Digits']</value>
      <webElementGuid>770de071-e3f3-4c84-add6-583fee23033a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
