<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Spesialis</name>
   <tag></tag>
   <elementGuidId>dde1f587-86d6-4a0f-9571-aa71c19c8065</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[246]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ts-wrapper.tom-select.w-full.single.plugin-dropdown_input.required.full.has-items.focus.input-active.dropdown-active > div.ts-dropdown.single.plugin-dropdown_input > div.dropdown-input-wrap > input.dropdown-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Select your specialty&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a5da8c97-5d7b-4582-8fae-a5060b9b4746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4d01681b-1bbd-4701-9c6f-67205cccf96e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c6af8d99-7aff-42d3-abb6-126c224bcf49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7818cde9-3d13-48fc-9326-f4719565ab49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>9c9aefa1-5ad7-40b3-ac8f-fec2bc1b112e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-input</value>
      <webElementGuid>30ec5fa8-9d7c-46bc-b8a4-8cf50e1d6995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select your specialty</value>
      <webElementGuid>719cc6a7-406a-4618-90e2-f3ca77f3d3ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-doctor-modal&quot;)/div[@class=&quot;modal-dialog modal-xl&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;px-5&quot;]/form[@class=&quot;form-doctor&quot;]/div[@class=&quot;grid grid-rows-3 grid-cols-4 gap-2&quot;]/div[@class=&quot;row-span-1 col-span-3&quot;]/div[@class=&quot;ts-wrapper tom-select w-full single plugin-dropdown_input required full has-items focus input-active dropdown-active&quot;]/div[@class=&quot;ts-dropdown single plugin-dropdown_input&quot;]/div[@class=&quot;dropdown-input-wrap&quot;]/input[@class=&quot;dropdown-input&quot;]</value>
      <webElementGuid>ee917a42-2ec6-4c7a-9d8e-fddaeb6ef878</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[246]</value>
      <webElementGuid>386acce3-6875-42c8-ae27-af158ee248ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='add-doctor-modal']/div/div/div/form/div[2]/div[4]/div/div[2]/div/input</value>
      <webElementGuid>83c750f8-24be-47e4-b968-4fa17e62ded9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/div/div[2]/div/input</value>
      <webElementGuid>8354f740-5f4b-463e-8995-bba14f987c50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Select your specialty']</value>
      <webElementGuid>a2005e66-880d-46ba-8764-3723a476a89a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
