<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_STR Number</name>
   <tag></tag>
   <elementGuidId>1a61c867-608f-418c-8714-10d08a2b25d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='str_number'])[11]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>form.form-doctor > div.grid.grid-cols-2.gap-4 > div.col-span-1 > input[name=&quot;str_number&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#add-doctor-modal input[name=&quot;str_number&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5db5c905-dd6e-4d2b-a0a1-82e5c898e6cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4ba3273c-be27-483b-b1f0-4b464551bf23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>str_number</value>
      <webElementGuid>cd32af01-81a7-485c-8a36-655fdae0f01a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8856bbe8-a539-4d95-af86-cc2a16377eed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-doctor-modal&quot;)/div[@class=&quot;modal-dialog modal-xl&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;px-5&quot;]/form[@class=&quot;form-doctor&quot;]/div[@class=&quot;grid grid-cols-2 gap-4&quot;]/div[@class=&quot;col-span-1&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>c0fdb91b-c27b-4cd9-ae4d-603bff92f48f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='str_number'])[11]</value>
      <webElementGuid>19bfadce-d56d-4a68-a891-78ce5f0bb823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='add-doctor-modal']/div/div/div/form/div[26]/div/input</value>
      <webElementGuid>f3e0f5d0-8826-47c9-b12f-a9e3b5234fb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[26]/div/input</value>
      <webElementGuid>ae27f8c1-a67a-48c8-b3b2-9bf56af0dffd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'str_number']</value>
      <webElementGuid>8cf1e0ac-fad6-45ed-913a-23dda3490818</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
