<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>change_status</name>
   <tag></tag>
   <elementGuidId>1da5ded3-daa0-4d70-8d9c-dc2560f12656</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='disable-68df5157b34c38b58e0e01e3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#disable-68df5157b34c38b58e0e01e3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;1 68df5156b34c38b58e0e01e2 68df5157b34c38b58e0e01e3 dr DoctorID khairul umam Dokter Umum khairulumam950@gmail.com View Edit&quot;i] >> internal:label=&quot;&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0bd8e0ca-165c-4b29-947c-0336e69369a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>95699082-13fb-4b92-9001-9539857093d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>59c973d8-ad78-44dd-ba9a-7644322d3976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>disable-68df5157b34c38b58e0e01e3</value>
      <webElementGuid>1a00e0c2-de09-494b-87e0-ee4cefd7f5aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;disable-68df5157b34c38b58e0e01e3&quot;)</value>
      <webElementGuid>f73e7967-e91d-4a4a-9e4d-3ab65412d543</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='disable-68df5157b34c38b58e0e01e3']</value>
      <webElementGuid>2026c0f3-6a55-415a-8f7a-35c2e01804d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/input</value>
      <webElementGuid>faeb1bf4-1291-4f8b-a3a1-efefa3b56a6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'disable-68df5157b34c38b58e0e01e3']</value>
      <webElementGuid>ad6c13f4-892f-4e59-a7ed-d627a1be94cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
