<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_STR Number</name>
   <tag></tag>
   <elementGuidId>650a7db6-772d-476b-a723-b4602232ba31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='str_number'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#form-690afa405f874c06f2063f53 > div.px-5 > div.grid.grid-cols-2.gap-4 > div.col-span-1 > input[name=&quot;str_number&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>form >> internal:has-text=&quot;Edit Juno Test's Data English Indonesian Personal Details Identification Photo *&quot;i >> input[name=&quot;str_number&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>29bd2aac-5d78-4c29-99c8-daed0a117f02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2d14bd2d-13d5-480c-b37b-5f9fa2779397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>str_number</value>
      <webElementGuid>d33ccb93-04cc-4e68-913d-bef8b4498375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f364efe6-c8ed-455e-b4e3-a5414b4af52e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>90000000002213</value>
      <webElementGuid>b2006e71-b833-4532-8e3c-86003b883c8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-690afa405f874c06f2063f53&quot;)/div[@class=&quot;px-5&quot;]/div[@class=&quot;grid grid-cols-2 gap-4&quot;]/div[@class=&quot;col-span-1&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>7d5b0ad6-fcd3-45a1-815e-b14f8857fcd7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='str_number'])[4]</value>
      <webElementGuid>b523331e-4bcc-4484-adfd-ed795bbebae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-690afa405f874c06f2063f53']/div[2]/div[24]/div/input</value>
      <webElementGuid>ae3990c3-d86b-4be5-9a92-06efd65e6ce9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/form/div[2]/div[24]/div/input</value>
      <webElementGuid>ddf91a87-63e4-4f51-8bcb-f0e81a419108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'str_number']</value>
      <webElementGuid>d0a8091b-ee08-4c06-b174-5e429714934a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
