<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_work_year</name>
   <tag></tag>
   <elementGuidId>24a577a0-be32-4aa6-a26a-fb05863a9675</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='work_year[]'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#form-690afa405f874c06f2063f53 > div.px-5 > div.grid.grid-cols-3.gap-4.work-experience.items-center > div > input[name=&quot;work_year[]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>form >> internal:has-text=&quot;Edit Juno Test's Data English Indonesian Personal Details Identification Photo *&quot;i >> input[name=&quot;work_year\[\]&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7638f7ea-0815-4d9c-9902-fde0714fb054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>5a18d576-994b-42fd-aa04-032cac58f5c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>work_year[]</value>
      <webElementGuid>81b473c9-94d8-4f58-9f34-8052c9f7096a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control h-10 pl-3 pr-6</value>
      <webElementGuid>3a1450ed-b681-4950-85c7-ee089df65e3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1980</value>
      <webElementGuid>16801690-d3d9-42ee-abb9-9593f8c07286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2025</value>
      <webElementGuid>e5661f2f-c35d-4691-9174-3c17064e3236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-690afa405f874c06f2063f53&quot;)/div[@class=&quot;px-5&quot;]/div[@class=&quot;grid grid-cols-3 gap-4 work-experience items-center&quot;]/div[1]/input[@class=&quot;form-control h-10 pl-3 pr-6&quot;]</value>
      <webElementGuid>ad4fc08f-461e-4d9b-b0d8-9119f5aa2bf3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='work_year[]'])[4]</value>
      <webElementGuid>993f9adf-f4a7-4cb5-bcbf-7fa753b1517f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-690afa405f874c06f2063f53']/div[2]/div[12]/div/input</value>
      <webElementGuid>7d225c0a-cfb9-4ac2-b34f-9e55b63f95d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/form/div[2]/div[12]/div/input</value>
      <webElementGuid>abf6d2ec-d5cd-424c-b295-d0948213748f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'work_year[]']</value>
      <webElementGuid>f27499b1-e362-412d-97df-b1e5d08f8c74</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
