<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bank Name</name>
   <tag></tag>
   <elementGuidId>7ea63597-4b12-49b1-a34b-e3dc435cc299</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='bank_name'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#form-690afa405f874c06f2063f53 > div.px-5 > div.grid.grid-cols-3.gap-4 > div > input[name=&quot;bank_name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>form >> internal:has-text=&quot;Edit Juno Test's Data English Indonesian Personal Details Identification Photo *&quot;i >> input[name=&quot;bank_name&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2864d9c7-e869-4d0d-be82-3f83e67e693c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>264f6e18-2c8e-49cf-83f8-bf29025bdfe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bank_name</value>
      <webElementGuid>d4117097-d72b-4080-a831-858efcfa0437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>41fa81ab-d64a-497f-9a79-611d33b5e222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>BCA</value>
      <webElementGuid>d1dff55f-8132-4d04-be11-d793cd89561d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-690afa405f874c06f2063f53&quot;)/div[@class=&quot;px-5&quot;]/div[@class=&quot;grid grid-cols-3 gap-4&quot;]/div[1]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>e2d7a91e-3af6-4ed0-bb20-2936dbf725f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='bank_name'])[4]</value>
      <webElementGuid>ff019294-3aef-406b-9234-2bc367f8a907</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-690afa405f874c06f2063f53']/div[2]/div[21]/div/input</value>
      <webElementGuid>0c1586c3-9e39-49bc-8a73-5dd16260dd22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/form/div[2]/div[21]/div/input</value>
      <webElementGuid>e525b3de-81e7-4e71-b282-ac482828942b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'bank_name']</value>
      <webElementGuid>54cd4e95-fd67-4312-8a76-ece58ec26205</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
