<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_status Inactive</name>
   <tag></tag>
   <elementGuidId>e0af3f38-22e0-46f0-b44b-403bdab01746</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='status-2'])[11]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#edit-6373121b5f5d4e796aa27aaf-modal > div.modal-dialog.modal-xs > div.modal-content > div.p-5 > form > div.mt-3 > div.flex.gap-5 > div.flex.items-center > #status-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=radio >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5380a263-82f5-40de-9b2e-daf3556026d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>status-2</value>
      <webElementGuid>2459d2a2-5863-492e-ae80-e54160bac206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>c3b5461d-9e57-4ba3-b7c4-8e1f10a6599d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>inactive</value>
      <webElementGuid>11009818-23ae-44ee-8f4e-073debf894b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>7d5d5801-92d0-4539-8491-4371de507e8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-4 h-4 text-blue-600 bg-gray-100 border-gray-300</value>
      <webElementGuid>e265c58b-cac7-4374-9591-8a9f3a1a31f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-6373121b5f5d4e796aa27aaf-modal&quot;)/div[@class=&quot;modal-dialog modal-xs&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;p-5&quot;]/form[1]/div[@class=&quot;mt-3&quot;]/div[@class=&quot;flex gap-5&quot;]/div[@class=&quot;flex items-center&quot;]/input[@id=&quot;status-2&quot;]</value>
      <webElementGuid>f4cf6776-d97f-4ab9-a41b-a726bcc7604c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='status-2'])[11]</value>
      <webElementGuid>c21e5970-2f16-42bf-a1cb-d93af1f4f8a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-6373121b5f5d4e796aa27aaf-modal']/div/div/div[2]/form/div[2]/div/div[2]/input</value>
      <webElementGuid>08b65e5a-8980-4b35-80e8-ecc54d8666d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/form/div[2]/div/div[2]/input</value>
      <webElementGuid>484b3941-35cb-453e-9868-0e104bf57875</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'status-2' and @type = 'radio' and @name = 'status']</value>
      <webElementGuid>5dc9db96-088b-466d-8726-e652974af962</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
