<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Day</name>
   <tag></tag>
   <elementGuidId>1ad2e23a-b9be-4949-afb5-de25a91346c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='calendar-daily']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#calendar-daily</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Day&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>19f6a0a2-73b5-4383-8e4c-38cd6000f42f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>calendar-daily</value>
      <webElementGuid>79a417cd-67d9-4ae0-aed3-01c100b543c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://backoffice-stg.digitalsekuriti.id/schedule/general-practitioner/calendar</value>
      <webElementGuid>cb204538-dc71-4868-8f2b-9037d2adef09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>3f153eb3-245e-4b6e-9dd5-cdd809e188a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    Day
                                </value>
      <webElementGuid>b3b32a73-c5a0-4e1f-9c3d-12aed05ca2b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calendar-daily&quot;)</value>
      <webElementGuid>65f8b271-ae7d-4189-b7a7-a456a507990d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='calendar-daily']</value>
      <webElementGuid>6f4cdc5f-abc0-4999-9070-181b6af11621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_431c4ba60af3db639266c070a8104aea']/ul/li/a</value>
      <webElementGuid>884f8a8b-f5bd-4787-9b37-4d603e7d511b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Day')]</value>
      <webElementGuid>2177e307-0537-4eec-a18b-796706e47408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::a[1]</value>
      <webElementGuid>056f3cf6-ce0f-4f45-9ed6-437e726af4d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Week'])[1]/preceding::a[1]</value>
      <webElementGuid>492765d4-243d-4db8-8ac0-fe7ffe8dd250</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Month'])[1]/preceding::a[2]</value>
      <webElementGuid>85bf3d5a-69c3-4e1a-9f0e-4053471dee1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://backoffice-stg.digitalsekuriti.id/schedule/general-practitioner/calendar')])[4]</value>
      <webElementGuid>1e9041bd-6da1-470e-97e6-23424f4206de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/ul/li/a</value>
      <webElementGuid>9cf0ee3d-2d0e-4348-a8db-e9d54a656e76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'calendar-daily' and @href = 'https://backoffice-stg.digitalsekuriti.id/schedule/general-practitioner/calendar' and (text() = '
                                    Day
                                ' or . = '
                                    Day
                                ')]</value>
      <webElementGuid>489c8cae-3d3f-4996-b2f5-2bb36b5c011f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
