<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Week</name>
   <tag></tag>
   <elementGuidId>9921c429-4ad6-4f0f-af32-62530b5e4719</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='calendar-weekly']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#calendar-weekly</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Week&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1260036c-2d8b-4c33-8198-27cd0db35995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>calendar-weekly</value>
      <webElementGuid>cd3848d1-303b-4326-9517-3c09ad373373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://backoffice-stg.digitalsekuriti.id/schedule/general-practitioner/calendar-weekly</value>
      <webElementGuid>69f14197-6ba4-43dd-a1cc-ad48049cb927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>00bc1add-61b0-445a-8964-8dee9bc544ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    Week
                                </value>
      <webElementGuid>ad20cbe3-b832-4dd3-8e55-a208fab09fa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calendar-weekly&quot;)</value>
      <webElementGuid>1bedbc04-4565-4bb5-b158-95d3f1e1c59e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='calendar-weekly']</value>
      <webElementGuid>b53f623d-d016-4950-9993-fd6b5fdf5ce1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_79152c41008b4f9599db50d561677a34']/ul/li[2]/a</value>
      <webElementGuid>b1de8c6f-0a7f-4bd0-87f0-65702851d29e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Week')]</value>
      <webElementGuid>d11d7f21-f620-4403-90f2-bfb0c6d95f67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Day'])[2]/following::a[1]</value>
      <webElementGuid>07047d01-4932-42cb-bfba-e477612fa256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Month'])[1]/preceding::a[1]</value>
      <webElementGuid>8a80d12e-dfab-489c-b78a-d74cdb4ef5a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Week']/parent::*</value>
      <webElementGuid>ebb26760-fa27-4a01-b7c7-c7a4aaf18866</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://backoffice-stg.digitalsekuriti.id/schedule/general-practitioner/calendar-weekly')]</value>
      <webElementGuid>5a582d65-c818-4677-a1f7-1a4880bc9329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/ul/li[2]/a</value>
      <webElementGuid>ee8810ff-16da-4d1d-9d6b-b7d60516e758</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'calendar-weekly' and @href = 'https://backoffice-stg.digitalsekuriti.id/schedule/general-practitioner/calendar-weekly' and (text() = '
                                    Week
                                ' or . = '
                                    Week
                                ')]</value>
      <webElementGuid>48821d36-30a6-4fc2-a79f-8457f3a1307b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
