<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save</name>
   <tag></tag>
   <elementGuidId>630e394e-e084-4b21-8e81-6e276a86b546</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Save&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>53322ca2-eedd-404e-b5aa-062982d669fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>46040606-9f8f-4f4a-a0b6-1564bd5673da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-white bg-primary focus:ring-4
                                    focus:outline-none font-medium rounded-lg
                                    text-sm inline-flex items-center px-5 py-2.5 text-center</value>
      <webElementGuid>53387a37-d6b2-42c9-87ec-e03bdb76264c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Save
                        </value>
      <webElementGuid>f47787fd-dae9-4879-9a75-329db4e9a0dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-692568dcb89201b0ac083352-modal&quot;)/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;p-6&quot;]/form[1]/div[@class=&quot;flex justify-end gap-5 mt-10&quot;]/button[@class=&quot;text-white bg-primary focus:ring-4
                                    focus:outline-none font-medium rounded-lg
                                    text-sm inline-flex items-center px-5 py-2.5 text-center&quot;]</value>
      <webElementGuid>c6bb0ef9-b662-40e3-a2d1-3a1cef5972c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[4]</value>
      <webElementGuid>43044f0b-526f-4f5b-88f0-a3785c3a648a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-692568dcb89201b0ac083352-modal']/div/div/div/form/div[2]/button[2]</value>
      <webElementGuid>9764d4c9-2159-4f1b-92ab-4d728929d050</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[3]/following::button[1]</value>
      <webElementGuid>ff70d5f8-8f15-4942-b7bc-d0dd61749e1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shift 16 (22.00 - 23.00)'])[4]/following::button[2]</value>
      <webElementGuid>4ceb75f1-6c71-4fb1-87d0-66eb62f76c58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/form/div[2]/button[2]</value>
      <webElementGuid>e6bb0ac1-f898-48ee-a988-33054e74741c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = '
                            Save
                        ' or . = '
                            Save
                        ')]</value>
      <webElementGuid>37226c34-60e8-445a-837d-c48d88d5f710</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
