<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Semakin di Devan</name>
   <tag></tag>
   <elementGuidId>2a0583f3-7eee-40e5-bd1f-0293591711c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#account-opt-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='account-opt-4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#account-opt-4</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cd33a98c-5eb2-4fe1-90a0-fbae1727196f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>68e4cd45af41d451d606a552</value>
      <webElementGuid>6a7e80aa-29cd-4d6a-8a63-66162f6f0815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option active</value>
      <webElementGuid>c0b6a39f-8fed-40be-9363-040317302ef6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>b74b3913-2d39-4a75-a0f3-fb7a4b86ff0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>account-opt-4</value>
      <webElementGuid>01dab8cd-6301-4c7e-9c0a-8fd456b8f518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4055ef7d-2a88-49b0-8ffd-ed33d62d16ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Semakin di Devan</value>
      <webElementGuid>c1d8ba3b-a84e-422c-af48-49bf7a7fbda0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;account-opt-4&quot;)</value>
      <webElementGuid>8c51c7e6-d758-4525-91ae-63729f0ac330</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='account-opt-4']</value>
      <webElementGuid>451997db-f0b3-46ce-8dcd-7fa0cf99e996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='account-ts-dropdown']/div[4]</value>
      <webElementGuid>17d870ca-bb62-46a9-87a7-4301497b3ede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Arjun Setyawan'])[2]/following::div[1]</value>
      <webElementGuid>93fbc477-aa30-461a-8c7c-ef63914512a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Arjun Setyawan tes 123'])[2]/following::div[2]</value>
      <webElementGuid>abbaa33b-5a08-456f-9610-346af23e8f9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='rin pus'])[2]/preceding::div[1]</value>
      <webElementGuid>a213c54a-09af-4b48-af61-8e825b9adc07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='khairul umam'])[2]/preceding::div[2]</value>
      <webElementGuid>27ff1dca-556b-49b6-9fae-2d7748ee353b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]</value>
      <webElementGuid>30c2780e-0051-4a17-8629-aeb3281a42bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'account-opt-4' and (text() = 'Semakin di Devan' or . = 'Semakin di Devan')]</value>
      <webElementGuid>c554f67b-dcf9-4054-9180-d9b3d00571d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
