<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Type the reason here</name>
   <tag></tag>
   <elementGuidId>4a068502-b35b-4200-a3b3-1066d20e5bbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//textarea[@id='reason'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#delete-692568dcb89201b0ac083354-modal > div.modal-dialog.modal-lg > div.modal-content > div.p-6 > form > div > #reason</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>44e72e96-8e9f-40fa-89da-9d5e3d8076ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reason</value>
      <webElementGuid>0a50500e-39b2-4f07-ade6-78ce7902ca78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reason</value>
      <webElementGuid>7e45700a-7848-408d-a96d-1c81e00d18e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>4939e833-9ea8-4ce5-9573-22e4e6355091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control w-full mt-3</value>
      <webElementGuid>519dacf1-4fbf-4c45-bf62-fbf4a1a35fbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Type the reason here</value>
      <webElementGuid>9d65a5e9-2a08-42fc-ad9a-1a616cef8334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;delete-692568dcb89201b0ac083354-modal&quot;)/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;p-6&quot;]/form[1]/div[1]/textarea[@id=&quot;reason&quot;]</value>
      <webElementGuid>1cad8d03-96a0-4507-b147-dc9fb38953e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//textarea[@id='reason'])[4]</value>
      <webElementGuid>e6afca7f-dc27-404c-aa4a-616545cc97a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='delete-692568dcb89201b0ac083354-modal']/div/div/div/form/div/textarea</value>
      <webElementGuid>493dd4c2-6bd1-49a4-a3b7-f3dea47de28f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::textarea[1]</value>
      <webElementGuid>18c02edf-2744-4822-8f4c-53344acad402</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[4]/preceding::textarea[1]</value>
      <webElementGuid>4877e1f7-965c-4205-91c7-b795241ba34c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes, Delete (1)'])[4]/preceding::textarea[1]</value>
      <webElementGuid>954a66c3-9e27-420a-9d4d-ab04f6c0bd5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/form/div/textarea</value>
      <webElementGuid>96f4f516-7519-4ec4-8f72-e91809952144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'reason' and @id = 'reason' and (text() = 'Type the reason here' or . = 'Type the reason here')]</value>
      <webElementGuid>e7347967-a7e9-4cdd-aa56-e96f9a6208b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
