<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>add_language</name>
   <tag></tag>
   <elementGuidId>ff504eba-9346-42e8-9739-d05a648c6e3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tomselect-3-ts-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tomselect-3-ts-control']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#tomselect-3-ts-control</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2f50d52c-f6b8-48c5-8de3-1c7bedd074a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ts-control</value>
      <webElementGuid>4749f05b-43e4-4fd4-8c24-bf1eaaaffe19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>cc091ea8-22fd-4423-a48a-ca1296eb3acf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>bc21e613-54f7-4dcb-9e93-a1f2fbc9a497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>666ed199-acdd-49c4-81a3-967c1b4822f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>tomselect-3-ts-dropdown</value>
      <webElementGuid>98e6ba9b-f0c4-43e0-9933-74a8093f0e97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tomselect-3-ts-control</value>
      <webElementGuid>5eb98009-de37-4a34-b38d-72959d9215f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>08171f12-ab7c-43ae-bccb-50b92644bff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>tomselect-3-opt-1</value>
      <webElementGuid>b5c23a9b-47eb-4f03-95e2-e4bb2ea4f482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>en</value>
      <webElementGuid>ae6138fd-9fa4-4b2e-bbf0-fd6c434ffb1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tomselect-3-ts-control&quot;)</value>
      <webElementGuid>673afbe5-ed5b-43dd-83a9-b3ae868085b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='tomselect-3-ts-control']</value>
      <webElementGuid>7edcb08f-589c-40f8-8056-dac694c86db1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='add-search-query-modal']/div/div/div[2]/form/div[5]/div/div</value>
      <webElementGuid>36422338-e39d-46db-8e1d-84471393c490</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Language'])[23]/following::div[2]</value>
      <webElementGuid>8350fec0-2e95-41f6-b2ba-953e9bf0873f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Urology'])[12]/following::div[3]</value>
      <webElementGuid>30235192-f4b0-488b-bc1f-637b55e0f8c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='en'])[23]/preceding::div[3]</value>
      <webElementGuid>8f65711b-2fa8-4b28-be8d-fddf21b52840</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/form/div[5]/div/div</value>
      <webElementGuid>975d16c8-3d37-4e40-afa8-21801803b62a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'tomselect-3-ts-control' and (text() = 'en' or . = 'en')]</value>
      <webElementGuid>7261c789-b5fe-4aed-b795-1516d4fb6c6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
