<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Add keyword</name>
   <tag></tag>
   <elementGuidId>c253c5b7-4d87-4e62-9a11-cfa6f8296581</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.create.active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tomselect-1-ts-dropdown']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Add test…&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>83b5ac03-7534-4ec9-809a-79fddb1cff0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>create active</value>
      <webElementGuid>a98a3d38-16df-4baa-9fdc-2b4bf7879e35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4206e8bd-73d0-4ed9-93c6-18306bfe9496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add test…</value>
      <webElementGuid>68135b6b-c3c7-41bc-83e7-8e2d5f36b85b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tomselect-1-ts-dropdown&quot;)/div[@class=&quot;create active&quot;]</value>
      <webElementGuid>be95773d-bdad-42c7-987e-c98ea6d8f16e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tomselect-1-ts-dropdown']/div</value>
      <webElementGuid>f2bdec56-52b2-4406-8f87-45405a95e952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ex: saraf, jiwa, tht (enter your own keyword)'])[11]/following::div[6]</value>
      <webElementGuid>e6a58842-f908-497c-a225-cbf9ad751c0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keyword'])[23]/following::div[6]</value>
      <webElementGuid>960fad77-8081-447c-8c9d-6db049a033c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No results found'])[1]/preceding::div[1]</value>
      <webElementGuid>d0665bf3-8582-4d12-9e78-1e9f836ade24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add']/parent::*</value>
      <webElementGuid>bb2dbb25-d5fa-4002-ac5b-0aea5468ddd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div</value>
      <webElementGuid>64e3c5c7-a80c-40a6-9770-30a11711c9d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Add test…' or . = 'Add test…')]</value>
      <webElementGuid>351afc2e-39bf-47ee-a59c-7efd125c29aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
