<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Regulation</name>
   <tag></tag>
   <elementGuidId>124cb221-5ea2-4142-89d8-9049cfb73f22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tomselect-6-ts-control > input.items-placeholder</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tomselect-6-ts-control']/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#tomselect-6-ts-control >> internal:attr=[placeholder=&quot;None&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0d0b17e1-9606-4ed0-a9f3-94f5274e7e50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>items-placeholder</value>
      <webElementGuid>52fde54f-45f6-4f8b-aad6-250ea9227492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>e6705665-255e-459a-833a-dc869a87398b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>None</value>
      <webElementGuid>8259c401-af8b-4520-a493-3bd1a76a1ea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tomselect-6-ts-control&quot;)/input[@class=&quot;items-placeholder&quot;]</value>
      <webElementGuid>be6d932f-82d6-4ba1-90ec-c9c8d6c68925</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tomselect-6-ts-control']/input</value>
      <webElementGuid>a6b64477-dac4-4d53-99cc-0deb9a988ed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[5]/div/div/input</value>
      <webElementGuid>8b4b16b7-8c19-468e-8b3b-c85c55b0d920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'None']</value>
      <webElementGuid>71fd4a95-3722-4410-94b4-87f6971f0824</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
