<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Language</name>
   <tag></tag>
   <elementGuidId>9602c8b4-79c5-46a2-9feb-3efead250633</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tomselect-5-ts-control > input.items-placeholder</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tomselect-5-ts-control']/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#tomselect-5-ts-control >> internal:attr=[placeholder=&quot;None&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6f8f3e2d-4a05-4196-b1bb-9854da07c1ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>items-placeholder</value>
      <webElementGuid>130bc219-8eef-48d2-8b73-5a4228987c14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>c81c883e-ba2c-40c2-8cb7-5dd2e325a348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>None</value>
      <webElementGuid>316a80a6-915d-4d3f-98be-8308610bcec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tomselect-5-ts-control&quot;)/input[@class=&quot;items-placeholder&quot;]</value>
      <webElementGuid>dd386b78-ac40-4648-a655-e403145954a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tomselect-5-ts-control']/input</value>
      <webElementGuid>47a0154e-01d4-4567-94e9-83acf4f28165</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[4]/div/div/input</value>
      <webElementGuid>7b384008-fba0-427c-921d-f0fb06f3a68f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'None']</value>
      <webElementGuid>c8a934e7-9fcc-4115-9b0f-79682838bec4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
