<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Description</name>
   <tag></tag>
   <elementGuidId>ad729b8e-d156-4baf-8c45-8ff032fa4b8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#add-search-query-modal > div.modal-dialog.modal-xs > div.modal-content > div.p-5 > form > div.mt-3 > input[name=&quot;description&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='description'])[11]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#add-search-query-modal input[name=&quot;description&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9dc886fe-7ae3-49ee-98f3-a78e9d0ffd52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>958a5ed0-e12e-4213-b9f0-432d0ab1b9c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>description</value>
      <webElementGuid>e1c3aff9-5b8d-4db1-bea5-e11e640bbb61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c8dcddbd-8413-457d-b06a-47a38a6a03f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-search-query-modal&quot;)/div[@class=&quot;modal-dialog modal-xs&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;p-5&quot;]/form[1]/div[@class=&quot;mt-3&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>be0c09ec-27dc-4777-b165-d3d19cb70765</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='description'])[11]</value>
      <webElementGuid>fc084391-6394-495f-8dec-1615b4f37473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='add-search-query-modal']/div/div/div[2]/form/div[2]/input</value>
      <webElementGuid>a2881022-9093-41f8-8e69-14e35f67a28f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/form/div[2]/input</value>
      <webElementGuid>d1f82c85-1d53-447e-b48d-fc0ee47dd5b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'description']</value>
      <webElementGuid>018e9244-c4dd-43d5-805a-71a383bc98bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
