<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Category</name>
   <tag></tag>
   <elementGuidId>7391fe0a-82c1-4d86-af64-40d9340126af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tomselect-1-ts-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tomselect-1-ts-control']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#tomselect-1-ts-control</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7ed8cb41-07c9-4ded-99e8-ec22360734dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ts-control</value>
      <webElementGuid>f8e17047-5a2d-4cc4-a3d3-c385b6a4a3fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>2683e2c6-dfcc-41ae-b7e1-857dcf96fdd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>b13ab8ab-5821-4518-a428-a8c9484e87ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4ac09514-117b-47aa-80d3-b4b42c53768b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>tomselect-1-ts-dropdown</value>
      <webElementGuid>443c6fca-2384-41a6-b4d7-a81ebfe08e9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tomselect-1-ts-control</value>
      <webElementGuid>b58346bf-f5ef-4629-a48c-0c87c9d27062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9859a207-6569-4058-9912-459a02b10986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>tomselect-1-opt-1</value>
      <webElementGuid>6acaf633-f3d5-4030-97b3-1b436450077c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Alergi dan Sistem Imun</value>
      <webElementGuid>f412949b-2665-4d26-8c9f-ce7b87a4af6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tomselect-1-ts-control&quot;)</value>
      <webElementGuid>dd5d4c39-af39-4276-8a7a-791c87082545</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='tomselect-1-ts-control']</value>
      <webElementGuid>d695cb9a-b776-4e08-941c-8f714b49fafd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Category'])[1]/following::div[2]</value>
      <webElementGuid>2acea9a0-79ee-4d80-9177-b6ecfa0a5162</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Answers'])[1]/following::div[8]</value>
      <webElementGuid>fb3473d7-8f8f-42d7-a89a-e85f1a50678e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alergi dan Sistem Imun'])[3]/preceding::div[3]</value>
      <webElementGuid>3041e773-ad23-4c19-bc3d-1ef4b38d4b23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div</value>
      <webElementGuid>fc2a7026-eff2-432b-9d50-20e976573219</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'tomselect-1-ts-control' and (text() = 'Alergi dan Sistem Imun' or . = 'Alergi dan Sistem Imun')]</value>
      <webElementGuid>b0d79794-1595-4940-baac-084fa67e2523</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
