<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Slug</name>
   <tag></tag>
   <elementGuidId>d9a1c915-e684-4042-9fd3-5753339b1516</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;slug&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='slug']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;slug&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c76ddb8f-f2ed-4d57-babb-db72852f46f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a299fe2a-a66f-47e6-b5cd-597a893844be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>slug</value>
      <webElementGuid>8f21fc16-05ce-4e1c-9ac7-eb5b813a1770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3ce642c0-a87a-4d92-bda9-94db08727bd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>benjolan-nyeri-di-sekitar-payudara</value>
      <webElementGuid>529dcfac-6318-4314-8162-3f870c2f49a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;light&quot;]/body[@class=&quot;py-5 md:py-0&quot;]/div[@class=&quot;flex overflow-hidden&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;col-span-12 lg:col-span-8 2xl:col-span-9&quot;]/div[@class=&quot;intro-y box lg:mt-5&quot;]/div[@class=&quot;p-5&quot;]/div[@class=&quot;answer-box&quot;]/form[@class=&quot;form-discussion&quot;]/div[@class=&quot;grid grid-cols-2 gap-4&quot;]/div[@class=&quot;mt-3&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>a777edec-1e9c-430c-b7cd-2a95eeab8bd5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='slug']</value>
      <webElementGuid>b025b870-54fc-4834-8258-850ee10db516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>ee0ae37f-893c-4ed1-99b7-ae25565a3b7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'slug']</value>
      <webElementGuid>4ebc85e1-bd98-49e0-9522-8f229e8ad4e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
