<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_language</name>
   <tag></tag>
   <elementGuidId>f5098f9c-8fe8-4e3f-ba70-767642b7b7fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#language-ts-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='language-ts-control']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=combobox[name=&quot;Rule&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2cbd85d8-1bea-4f3f-b9bf-94868e93a961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ts-control</value>
      <webElementGuid>2191787d-d55f-4b59-84f4-83b6093d063c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>3efc75cc-c414-45a6-a83e-481692caa4fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>c4a54026-7b07-4e78-9db3-28a4c3256d95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>51c94ca0-6f2d-413b-afc4-33afcef2d6f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>language-ts-dropdown</value>
      <webElementGuid>f7f2c4a1-ef37-46d1-a393-b7e9f7aab529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>language-ts-control</value>
      <webElementGuid>83cf5216-c615-4d2a-a3b2-b02f6bf32fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>language-ts-label</value>
      <webElementGuid>f7b409a5-270b-45cf-9957-161275969d67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7bf609a9-82fa-4b9f-ae94-09f04583bd6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>language-opt-1</value>
      <webElementGuid>70463c1b-0a22-4d93-bbd4-4646ff2ebfa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                EN
                            </value>
      <webElementGuid>ae50516e-978d-48de-b335-db5d99087682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;language-ts-control&quot;)</value>
      <webElementGuid>6f70f79f-1592-4626-a207-0744e7fd484f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='language-ts-control']</value>
      <webElementGuid>eb7bf899-76d1-4048-968f-f61b6130150c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Language'])[1]/following::div[2]</value>
      <webElementGuid>5a4d2350-9f9e-469f-a48a-80e354bb6717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rule'])[1]/following::div[3]</value>
      <webElementGuid>9cc2a76f-d6ac-4433-84c8-726dc228a03b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EN'])[3]/preceding::div[3]</value>
      <webElementGuid>0111fde5-f5e7-448d-aa18-6543af47b034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div/div</value>
      <webElementGuid>d487b3ba-6aa9-4378-baf1-232c4af9f72b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'language-ts-control' and (text() = '
                                EN
                            ' or . = '
                                EN
                            ')]</value>
      <webElementGuid>35ac2f99-417d-4b3b-8df6-e3ca987b3fce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
