<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_EN</name>
   <tag></tag>
   <elementGuidId>f633621a-830a-403b-bce3-e8e701f2863a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#language-opt-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='language-opt-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#language-opt-1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b8baa311-1990-4f62-842d-b92d192f07d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>en</value>
      <webElementGuid>d8f6e33e-ed09-4221-8bf2-967c863e3718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option selected active</value>
      <webElementGuid>01a99da2-69c4-43eb-b898-9f2b0539e5f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>0c01012e-e98d-42ff-841f-8bbb15c09854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>language-opt-1</value>
      <webElementGuid>3f8b1ce2-80ea-491e-98da-833db1a8586a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4e9fd495-4525-4f75-be42-de5f12bb59e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                EN
                            </value>
      <webElementGuid>eb782c98-1b1c-4832-b20b-376dba663f00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;language-opt-1&quot;)</value>
      <webElementGuid>b9f2bd0a-6d7e-494d-91bd-d9e738ff401c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='language-opt-1']</value>
      <webElementGuid>8245cf78-97d3-4175-9a1f-2c24e4d89d14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='language-ts-dropdown']/div</value>
      <webElementGuid>9a97ab90-7ae8-4c14-817d-aad00823f5b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EN'])[2]/following::div[4]</value>
      <webElementGuid>c5398267-bf4e-4138-9c6e-45d1b3ef73de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Language'])[1]/following::div[7]</value>
      <webElementGuid>8805899f-6f39-49f7-9b94-dbd0bdd6166d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID'])[2]/preceding::div[1]</value>
      <webElementGuid>984e35c8-60a9-4e3c-9474-70c986b16344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regulation'])[1]/preceding::div[2]</value>
      <webElementGuid>4224633b-e85b-4a59-92a1-080266a28241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[2]/div</value>
      <webElementGuid>8d57caa7-fef0-40e6-b5da-878efad54701</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'language-opt-1' and (text() = '
                                EN
                            ' or . = '
                                EN
                            ')]</value>
      <webElementGuid>e37e40c8-5769-41b9-a1f7-da423765180f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
