<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Month</name>
   <tag></tag>
   <elementGuidId>85e9d315-50a2-4469-9cb2-892e247faa83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='calendar-monthly']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#calendar-monthly</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Month&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6c46b4e9-afb1-4b75-b12d-1dc389f60c28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>calendar-monthly</value>
      <webElementGuid>101409b5-fbbd-4312-83d9-984f95385575</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://backoffice-stg.digitalsekuriti.id/schedule/specialist/calendar-monthly</value>
      <webElementGuid>2745ea30-428a-457c-a926-ab79b6e049e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>d13d29a5-cd89-4b6a-aa0c-ecd14d973e5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    Month
                                </value>
      <webElementGuid>aa7fbad2-de38-4213-9ced-6b83a474b706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calendar-monthly&quot;)</value>
      <webElementGuid>faffd105-6547-42d9-ba3d-c1023ed0277a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='calendar-monthly']</value>
      <webElementGuid>f3888479-7ae2-45af-bdaa-038967f53a31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_ec923d59041052efc0ffce85e4abd9c7']/ul/li[3]/a</value>
      <webElementGuid>ee8cc2f7-9b48-4c76-aa9c-4b48aa15e6a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Month')]</value>
      <webElementGuid>baef09be-7552-4b18-9162-80b4d8119344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Week'])[1]/following::a[1]</value>
      <webElementGuid>55c0b030-5e1c-44c7-b7ad-59dfa7767994</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Day'])[2]/following::a[2]</value>
      <webElementGuid>baf2b504-aa74-4d1f-9fd6-fb1e1d5277bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Month']/parent::*</value>
      <webElementGuid>6a447a22-878a-483e-894b-550ea45e072b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://backoffice-stg.digitalsekuriti.id/schedule/specialist/calendar-monthly')]</value>
      <webElementGuid>45948f12-f204-46d3-beeb-b8128396d669</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/ul/li[3]/a</value>
      <webElementGuid>64b335cb-53e8-48ed-aac1-2b79ab5dffe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'calendar-monthly' and @href = 'https://backoffice-stg.digitalsekuriti.id/schedule/specialist/calendar-monthly' and (text() = '
                                    Month
                                ' or . = '
                                    Month
                                ')]</value>
      <webElementGuid>d4573f80-2ba5-4992-b476-02eadddd2d29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
