<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Shift 15 (21.00 - 22.00)</name>
   <tag></tag>
   <elementGuidId>48b423fa-98f7-40ff-a22a-b6faaf9fd2bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#shift-opt-12</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shift-opt-12']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#shift-opt-12</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2e4fd2aa-8c04-4df0-ad7d-11f294794e5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>53e4c3a8-cb47-4461-b582-e502ea664613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option active</value>
      <webElementGuid>f7f71086-31ed-40cc-b9ac-78c6fa980026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>1e198505-39d3-468c-8691-af9af1900d74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>shift-opt-12</value>
      <webElementGuid>67ebe0f9-5962-48da-818c-33bc45ea3f22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>33f3860e-f998-4830-8059-276e7dab5917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                        Shift 15 (21.00 - 22.00)
                                    </value>
      <webElementGuid>c139cdb1-3d6f-4849-8d79-87cd48192b76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shift-opt-12&quot;)</value>
      <webElementGuid>bb8fb8b5-0a9c-43ae-8677-d8e29c144ce4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='shift-opt-12']</value>
      <webElementGuid>632b89ac-d2b6-44de-b64d-0af5d3c25db8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shift-ts-dropdown']/div[12]</value>
      <webElementGuid>4373bf70-a785-42cd-bd6e-4dbc35824e38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shift 14 (20.00 - 21.00)'])[4]/following::div[1]</value>
      <webElementGuid>3df07aff-1972-41ba-9742-9fb7ddc935ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shift 13 (19.00 - 20.00)'])[4]/following::div[2]</value>
      <webElementGuid>425daf8a-aae5-48cd-90c0-047509021984</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shift 16 (22.00 - 23.00)'])[4]/preceding::div[1]</value>
      <webElementGuid>5d5aa0f3-a254-45ce-b44e-93f8f49f03ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[3]/preceding::div[2]</value>
      <webElementGuid>b02e6745-a30e-47b9-8fc7-0c927f6d50d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]</value>
      <webElementGuid>04c552a6-84a8-4645-ac37-e4fcb7d41358</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'shift-opt-12' and (text() = '
                                        Shift 15 (21.00 - 22.00)
                                    ' or . = '
                                        Shift 15 (21.00 - 22.00)
                                    ')]</value>
      <webElementGuid>27183914-abeb-4cf3-b288-588c11f4ac5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
