<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_shift</name>
   <tag></tag>
   <elementGuidId>7cbd14dc-c7e1-4eb1-a6c6-a86dddba590c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-692800e36a6bdd4a980956a2-modal > div.modal-dialog.modal-lg > div.modal-content > div.p-6 > form > div.grid.grid-cols-2.gap-4 > div.flex.flex-col > div.ts-wrapper.w-full.tom-select.mt-1.single.plugin-dropdown_input.full.has-items > #shift-ts-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='shift-ts-control'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#shift-ts-control >> nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2bc87079-de03-4007-ab00-8610f1ecd340</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ts-control</value>
      <webElementGuid>9444bd61-7576-482a-9b7d-1ebae4c5f01d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>08c35f06-4198-4c2d-886a-1fd78a002b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>9bb1d1ca-9f98-4044-8d0a-4caafb04fb49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5fd236ba-f8d9-4bd7-a5b7-93124b843fda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>shift-ts-dropdown</value>
      <webElementGuid>c87f84f9-a765-40e4-af7d-11e7d6e477a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>shift-ts-control</value>
      <webElementGuid>14a71fce-f385-4247-8891-f7be966494f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e2ee220f-b81e-4cc7-be87-981dd5aaa6c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                        Shift 1 (07.00 - 08.00)
                                    </value>
      <webElementGuid>4a3c7fe1-6e0e-4192-a6a0-a4247384fe88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-692800e36a6bdd4a980956a2-modal&quot;)/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;p-6&quot;]/form[1]/div[@class=&quot;grid grid-cols-2 gap-4&quot;]/div[@class=&quot;flex flex-col&quot;]/div[@class=&quot;ts-wrapper w-full tom-select mt-1 single plugin-dropdown_input full has-items&quot;]/div[@id=&quot;shift-ts-control&quot;]</value>
      <webElementGuid>990dc167-87a2-414e-9143-806c52681076</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='shift-ts-control'])[3]</value>
      <webElementGuid>020d8720-d8aa-4c0f-b7e4-4f221e2f06c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-692800e36a6bdd4a980956a2-modal']/div/div/div/form/div/div[2]/div/div</value>
      <webElementGuid>6513655c-add3-4339-84d0-d61d4080adef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No appointment on this schedule'])[3]/following::div[5]</value>
      <webElementGuid>dc320ea3-890d-48f5-b695-4f029cd726f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Schedule'])[5]/following::div[7]</value>
      <webElementGuid>34c52a8f-1a65-4d9a-8f90-64e744f92644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[3]/preceding::div[5]</value>
      <webElementGuid>0c500a07-9a04-466e-9f8b-71db67fdaa89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/form/div/div[2]/div/div</value>
      <webElementGuid>c9ee6a3d-db43-4f44-b0fc-2734610c45bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'shift-ts-control' and (text() = '
                                        Shift 1 (07.00 - 08.00)
                                    ' or . = '
                                        Shift 1 (07.00 - 08.00)
                                    ')]</value>
      <webElementGuid>22a947c2-34bb-45e3-a8d6-635aa90a345f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
