<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_reason</name>
   <tag></tag>
   <elementGuidId>dd8196bc-4e01-4309-8736-1b3c26da7e4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#delete-2025-11-27-modal > div.modal-dialog.modal-lg > div.modal-content > div.p-6 > form > div > #reason</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//textarea[@id='reason'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>940f5505-bfed-4bae-8bba-89df2a4532c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reason</value>
      <webElementGuid>0cd022b5-295e-494a-9287-dc43df1a8015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reason</value>
      <webElementGuid>bd060fc6-84e6-4b2e-9283-4b8afa1d3f30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>ba977f9a-cb92-4a99-acbe-d78b06d4b3ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control w-full mt-3</value>
      <webElementGuid>78bb9d4c-c28c-4150-816e-d910f3156a1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Type the reason here</value>
      <webElementGuid>e924513e-1dd4-4b30-9779-1c71abb020bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;delete-2025-11-27-modal&quot;)/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;p-6&quot;]/form[1]/div[1]/textarea[@id=&quot;reason&quot;]</value>
      <webElementGuid>c288925c-9be3-42bc-aeed-0a1808a978af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//textarea[@id='reason'])[4]</value>
      <webElementGuid>173d3c72-adfd-4c9d-8eca-c1f815a88e44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='delete-2025-11-27-modal']/div/div/div/form/div/textarea</value>
      <webElementGuid>6953e836-c051-4d2d-86d8-15c32fc92c44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::textarea[1]</value>
      <webElementGuid>b568ca48-539f-4616-a6f7-5ea51a02c133</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[4]/preceding::textarea[1]</value>
      <webElementGuid>b225ed7c-efe6-48ed-a1ab-ba5260675c16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes, Delete (1)'])[4]/preceding::textarea[1]</value>
      <webElementGuid>5ebfd943-7c1d-49ba-81f2-16304a4a1d5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/form/div/textarea</value>
      <webElementGuid>7ab0e242-84e1-4f06-a2ca-fd90d933fda6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'reason' and @id = 'reason' and (text() = 'Type the reason here' or . = 'Type the reason here')]</value>
      <webElementGuid>139f5074-ee50-408a-9f2a-f1fc32e0281f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
