<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Thumbs Down</name>
   <tag></tag>
   <elementGuidId>8106cf4a-9d6c-4d8d-99b8-de1154f2b959</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rating-opt-3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#rating-opt-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#rating-opt-3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>511b1bb5-2f7d-4bb8-8777-8b25b9d74e46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>dislike</value>
      <webElementGuid>89306d54-61cc-430a-85c8-eb73d3335fd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option active</value>
      <webElementGuid>9b45c113-7f00-4e31-9c4c-0bf3b4556c65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>b569aeb1-c6a8-4533-b711-580b427f6589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rating-opt-3</value>
      <webElementGuid>8b24cfea-95ef-4a97-a4bf-2d055e29fdac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1666c424-9564-40b3-b961-996b526e9776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thumbs Down</value>
      <webElementGuid>83c04840-5c27-4dc2-a5d6-f48dc42e7271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rating-opt-3&quot;)</value>
      <webElementGuid>42ed2a6c-c7c2-4802-9165-865d34458178</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='rating-opt-3']</value>
      <webElementGuid>ab203008-1328-4cb0-8150-c1f01c3eec40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rating-ts-dropdown']/div[3]</value>
      <webElementGuid>afc359ab-a9eb-4410-9807-f40295cf80f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thumbs Up'])[2]/following::div[1]</value>
      <webElementGuid>277f8e20-9282-4f10-b809-3b3c53484e98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Rating'])[3]/following::div[2]</value>
      <webElementGuid>ab054dc6-57b1-48e0-b2e0-9ef4373b0998</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All User Review'])[2]/preceding::div[1]</value>
      <webElementGuid>19defd0c-dd2a-4d97-9d42-bd4e784fcbe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rating &amp; Review >'])[1]/preceding::div[7]</value>
      <webElementGuid>84fcf932-596c-4ba3-a6b2-85a16bf7e313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[3]</value>
      <webElementGuid>d7c669be-6110-4ac1-8059-2b0e178d2767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'rating-opt-3' and (text() = 'Thumbs Down' or . = 'Thumbs Down')]</value>
      <webElementGuid>5a4b1759-d4e6-4f1d-8af8-a71e860765cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
